Feat/setup nav bar
IIION/Workade pull request #1
Opened 2022-10-18 15:04 UTC by BrightHyeon

# 배경
- 메인 홈 화면에 네비게이션 바와 상단 인삿말 부분이 적용되어야 함.

# 작업 내용
- SceneDelegate에서 window의 rootViewController를 UINavigationController(rootViewController: HomeViewController)로 변경.
- 네비게이션 바의 로고이미지와 프로필 버튼 구성.
- 로고이미지의 경우, isEnabled = false를 통해 touch highlight가 일어나지않도록 함.
- 추후 디자이너가 올릴 원본 이미지와 테스트용 Temp이미지의 이름이 겹치지않도록 임시로 이미지이름 뒤에 Tamna 붙임.
- "반가워요" 인삿말 레이블 추가 및 오토레이아웃 적용.
- font는 추후 디자인 시스템 적용 후 반영 예정.
- extension UIView -> addSubviews(_ views:) 메서드 추가
- extension UIImage -> original() 메서드 추가

# 테스트 방법
- 시뮬 켜서 육안으로 확인 가능.

# 리뷰 노트
- setupLayout이란 메서드 안에 addSubview메서드와 오토레이아웃관련 메서드를 함께 넣었습니다. 오토레이아웃은 반드시 addSubview된 후에 적용되어야 런타임에러가 나지않기 때문에 순서를 보다 확실히 보여주기위해 일단 넣어봤는데 다른 좋은 방법있을지 리뷰 부탁드려요

# 스크린샷
<img src="https://user-images.githubusercontent.com/95853235/196467462-8a2a7b26-1482-4ff3-9461-b9a5ee27c6d3.png" width=300>

2022-10-18 15:22 UTC, jeohong reviewed
[P1] PR컨벤션에 맞게 PR Title 제목을 문장형식으로 바꾸면 좋을것 같습니다! 탐나 수고하셨습니다 깔끔한 코드!

2022-10-18 15:22 UTC, jeohong commented on Workade/Views&ViewModels/Home/HomeView.swift
> +    private func setupLayout() {
[P5] 저같은 경우는 configureUI() 함수로 작성했는데 
다음 회의때 컨벤션에 대해 이야기를 나눠도 좋을것 같습니다!

2022-10-18 15:22 UTC, jeohong commented on Workade/Views&ViewModels/Home/HomeView.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
[P5] AutoLayout과 관련된 코드는 Layout 설정 함수에서 한번에 관리하는게 좋을까요 아니면 변수에 이렇게 작성하는게 좋을까요? 이것도 내일 한번 이야기 나눠봐요!

2022-10-18 15:36 UTC, BrightHyeon commented on Workade/Views&ViewModels/Home/HomeView.swift
> +    private func setupLayout() {
오오 좋습니당! 이런 함수는 이름 통일시키는게 좋겠군요~!

2022-10-18 15:37 UTC, BrightHyeon commented on Workade/Views&ViewModels/Home/HomeView.swift
> +        label.translatesAutoresizingMaskIntoConstraints = false
좋아용~~ 굳굳

2022-10-18 15:44 UTC, E-know requested changes

2022-10-18 15:44 UTC, E-know commented on Workade/Extentions/UIImage+.swift
> +    }
[P1] original 이라는 함수는 어떤 것을 의미하는지 잘 모르는 것 같습니다. 함수명은 동사형으로 시작하는 것을 권장합니다.

2022-10-18 15:44 UTC, E-know commented on Workade/Views&ViewModels/Home/HomeView.swift
> +        welcomeLabel.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -20).isActive = true
[P3] NSLayoutConstraint.activate 를 써야 할지 내일 한번 고민해보면 좋을 것 같습니다.

2022-10-18 15:44 UTC, E-know commented on Workade/Extentions/UIView+.swift
> +    }
[P2] 추가적인 함수를 구현하신 이유가 있으실까요?

2022-10-18 15:49 UTC, BrightHyeon commented on Workade/Extentions/UIImage+.swift
> +    }
setOriginal(직역 -> 원본으로 설정)으로 수정하겠습니다!

2022-10-18 16:00 UTC, BrightHyeon commented on Workade/Extentions/UIView+.swift
> +    }
뷰컨트롤러에 서브뷰들이 많아지다보면 늘어나는 서브뷰만큼 addSubview() 메서드를 나열하게됩니다. 
불필요한 좁고 긴 메서드 나열이 될 것 같아서 배열로 받을 수 있도록 확장했습니다!

2022-10-18 16:13 UTC, BrightHyeon commented on Workade/Extentions/UIView+.swift
> +    }
지금 생각으론 어차피 모두 오토레이아웃으로 구성할 예정이라면, 추후 저 for문 안에 view.translatesAutoresizingMaskIntoConstraints = false 를 넣어서 반복되는 로직을 한 번에 처리하고 싶습니다. 의견 부탁드릴게요!

2022-10-18 16:30 UTC, E-know commented on Workade/Extentions/UIView+.swift
> +    }
한번 다음 스크럼때 나눠보면 좋을 것 같습니다!

2022-10-19 03:20 UTC, hs-ryu reviewed
확인했습니다. 별다른 리뷰는 없습니다.

2022-10-20 06:29 UTC, E-know approved these changes
확인 완료했습니다!!

2022-10-20 06:30 UTC, merged