✨ 체크리스트 디테일 뷰를 구현하였습니다.
IIION/Workade pull request #10
Opened 2022-10-22 10:25 UTC by DevLuce

# 배경
- CheckListDetailView UI를 구현하였습니다.

# 작업 내용
- CheckListDetailView의 UI를 구성하였습니다.

# 테스트 방법
- 방법 1. SceneDelegate 파일에서 NavigationController 내에 CheckListDetailView 로 수정하여 실행합니다.
- 방법 2. 프리뷰 코드를 활용해 확인할수 있습니다.

# 리뷰 노트
- 현재 임시데이터를 넣어놓은 상태입니다. 추후 변경될 부분은 주석으로 달아 놓았습니다.
- 우측 아래에 원버튼이 완료되지 않았습니다. 추후 재사용될 부분이므로 재사용 버튼이 생성되면 변경하겠습니다.
- 아직 CRUD 기능은 추가하지 않았습니다.

# 스크린샷
<img width="300" alt="image" src="https://user-images.githubusercontent.com/56063805/197334201-5526939e-6626-43af-9900-fa3305a2cac5.png">

2022-10-22 11:03 UTC, hs-ryu commented
확인 완료했습니다. 별다른 리뷰 사항 없습니다.

2022-10-22 11:09 UTC, jeohong approved these changes
LGTM 👍

2022-10-22 11:58 UTC, E-know requested changes

2022-10-22 11:58 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
> +}
[P2] 저희 앱 최소버전이 14.0인데 13.0 이상을 검사할 필요가 있을까요??

2022-10-22 11:58 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +@available(iOS 13.0.0, *)
[P2] 이 또한 마찬가지 입니다!

2022-10-22 11:58 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +        Task(content: "DSLR 카메라", done: true)
[P3] 멀티 쓰래드 작업하는 함수 이름이 Task인데 나중에 겹치면 혼돈이 올 것 같습니다. Task 대신에 다른 이름은 어떤가요?

2022-10-22 11:59 UTC, E-know commented
[P4] PR내용 > 테스트 방법에 `CheckListDetailView` 대신에 `CheckListDetailViewController` 수정 부탁드립니다.

2022-10-22 11:59 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
> +}
프리뷰하려고 넣어놓은 코드인데 지우겠습니다!

2022-10-22 12:00 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +        Task(content: "DSLR 카메라", done: true)
아하 그렇군요! 바꾸겠습니다

2022-10-24 16:38 UTC, E-know approved these changes

2022-10-24 16:38 UTC, merged