✨ FirebaseMangager와 FirestoreDAO/DTO를 생성했습니다.
IIION/Workade pull request #103
Opened 2022-11-28 12:42 UTC by E-know

# 배경
- Firebase 사용으로 사용자 인증 및 지역별 이름을 알아야 했습니다.

# 작업 내용
- 구글로그인 구현
- 애플로그인 구현
- Firestore 연결하기 위한 DAO DTO 구현

# 테스트 방법
- 전체적인 로직 연결은 추 후에 View를 합치는 과정에서 진행됨에 따라 테스트 방법은 없습니다.
- 함수 설명 적당 여부

# 리뷰 노트
- 코드 컨벤션 준수 여부

2022-11-28 18:36 UTC, BrightHyeon reviewed
전체적으로 주석설명이 많이 없어요 😂 Firebase 로직은 저처럼 경험이 없는 팀원들의 경우 이해하기힘든데, 그래서 리뷰하기가 힘든것같아융

2022-11-28 18:36 UTC, BrightHyeon commented on Workade/Extentions/Encodable+.swift
> +        return dictinoary
[P1] dictionary 오타만 수정해주세용~!

2022-11-28 18:36 UTC, BrightHyeon commented on Workade/Models/UserModel.swift
> +    case designer = "디자인"
[P1] developer 오타만 수정해주세요!

2022-11-28 18:40 UTC, hs-ryu requested changes
해당 브랜치에서 코드를 다운로드 받아 실행시켜보면 에러가 발생합니다. GoogleService-Info.plist는 드롭박스에 올려 놓으신것을 넣었구요. 
<br>
<img width="200" alt="스크린샷 2022-11-29 오전 3 24 08" src="https://user-images.githubusercontent.com/75309495/204352571-73584e9b-39e2-47c1-a172-0f141e5411db.png">
<br>
관련하여 에러를 찾아봤는데, GoogleService-Info.plist에 문제가 있는듯 합니다. 혹시 다시 받아서 드롭박스에 넣어주실 수 있으실까요?

2022-11-28 18:49 UTC, BrightHyeon commented on Workade/Models/UserModel.swift
> +}
[P5] 특정 지역의 ActiveUser들의 직업은 User 컬렉션에서 뽑아내는건가요?

2022-11-28 18:50 UTC, E-know commented
> 전체적으로 주석설명이 많이 없어요 😂 Firebase 로직은 저처럼 경험이 없는 팀원들의 경우 이해하기힘든데, 그래서 리뷰하기가 힘든것같아융

앗 주석을 깜빡.... 주석 넣겠습니다.

2022-11-28 18:50 UTC, hs-ryu commented on Workade/Managers/FirestoreManager.swift
> +    func setLinstener(collectionName: String, listenderAction: @escaping (QuerySnapshot?, Error?) -> Void) -> ListenerRegistration {
[P5] 뭔가 listener 오타난거 같은데 맞나요?

2022-11-28 19:02 UTC, hs-ryu commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +    lazy private var guideLabel: UILabel = {
[P5] 순수 질문인데, 우리 다른 팀원들은 private lazy var 이런 순서로 코드를 작성하는데, 토비는 lazy private var 처럼 쓰시더라구요. 접근 제어자를 보통 어떤 순서에 집어 넣는게 맞는건가요??

2022-11-28 19:18 UTC, BrightHyeon commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +    }()
[P3] lazy 키워드 없이 private let으로 선언해도 될 것 같아용!

2022-11-28 19:18 UTC, BrightHyeon commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +class LoginNextButtonView: UIView {
[P5] 혹시 UIButton으로 만들지않고, UIView + tapGestureRecognizer형태로 만든 이유가 있으실까용~?

2022-11-28 19:18 UTC, BrightHyeon commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +    init(tapGesture: @escaping () -> Void) {
[P5] 오 이렇게도 초기화할 때 액션을 넘기는 방법도 있군용~!! 배워갑니당ㅎ

2022-11-28 19:18 UTC, BrightHyeon commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +    let tapGesture: () -> Void
[P3] private 하게 접근 수준 설정하는 것은 어떤가용~? 초기화 구문 때 넘김으로써 다른 곳에서는 호출하지못하도록 제한할 수 있다는 장점이 생길 것 같아서요~!

2022-11-29 04:11 UTC, DevLuce requested changes
고생하셨습니다! 빅썬 리뷰 마찬가지로 .gitignore에 GoogleService-Info 가 들어가있어서 따로 공유가 필요할 거 같습니다!
그리고 파이어베이스 콘솔에 저희 팀원들 초대 가능할까요? DB 구조도 같이 보면 좋을것 같아서요!

2022-11-29 04:11 UTC, DevLuce commented on Workade/Models/UserModel.swift
> +}
[P3] ActiveUser가 User를 참조해서 name, email, job의 정보를 가져오는게 필요할거 같습니다! 그리고 active가 시작된 timestamp도 필요할거 같아요 :)

2022-11-29 04:11 UTC, DevLuce commented on Workade/Models/UserModel.swift
> +}
[P5] Region의 한국어 rawValue가 필요하지 않을까요?

2022-11-29 04:11 UTC, DevLuce commented on Workade/Views&ViewModels/Login/Element/JobPickerScrollView.swift
> +    private var currentJobTitle: String? = nil
[P3] 이 중 3개의 변수가 사용되지 않고 있는데 추후에 사용될 변수들인가요?

2022-11-29 04:11 UTC, DevLuce commented on Workade/Views&ViewModels/Login/Element/LoginButtonView.swift
> +        textLabel.text = guideance
[P3] image와 text를 세팅하는 부분은 setupData() 와 같은 다른 메소드에 넣는 것을 어떨까요?

2022-11-29 04:11 UTC, DevLuce commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +    }
[P4] 외부에서 호출하는 함수인가요? 그럼 isAbleToSignup : Bool 변수를 인자로 넘겨주어서 아래와 같이 로직을 구성하는 건 어떨까요?
```Swift
guideLabel.isHidden = !isAbleToSignup
isUserInteractionEnabled = isAbleToSignup
backgroundColor = isAbleToSignup ? .blue : .gray
```

2022-11-29 05:47 UTC, E-know commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +    lazy private var guideLabel: UILabel = {
아뇨 딱히 의미는 없습니다. 근데 코드 컨벤션상 private lazy var 로 하겠슴돠

2022-11-29 06:22 UTC, E-know commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +    init(tapGesture: @escaping () -> Void) {
단점은 콜백지옥에 빠질 위험이 있습니다.

2022-11-29 06:23 UTC, E-know commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +class LoginNextButtonView: UIView {
음. 사실 애니메이션을 적용시켜야 한다는 생각에 무지성 UIView로 시작한 감이 없지 않아 있습니다. ㅠㅠ Button으로 다시 구성할까요?

2022-11-29 06:27 UTC, E-know commented on Workade/Views&ViewModels/Login/Element/JobPickerScrollView.swift
> +    private var currentJobTitle: String? = nil
파베에 Firestore에 한글이 적용되나 조금 걱정이 되지만 우선 적용하겠습니다.

2022-11-29 06:27 UTC, E-know commented on Workade/Models/UserModel.swift
> +}
파베에 Firestore에 한글이 적용되나 조금 걱정이 되지만 우선 적용하겠습니다.

2022-11-29 06:28 UTC, E-know commented on Workade/Views&ViewModels/Login/Element/JobPickerScrollView.swift
> +    private var currentJobTitle: String? = nil
앗 삭제하겠습니다.

2022-11-29 06:38 UTC, DevLuce commented on Workade/Models/UserModel.swift
> +}
아하! 넵! 그리고 전라도의 영문표기법이 틀린거 같습니다! 전라북도에 오타도 있고.... 설마 이게 지역감ㅈ....읍읍

2022-11-29 06:58 UTC, DevLuce approved these changes
확인했어요!! 고생하셨어용 🫰

2022-11-29 07:25 UTC, BrightHyeon commented on Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
> +class LoginNextButtonView: UIView {
UIButton도 UIButton(손주) - UIControl - UIView(할머니)
상속 구도라서 애니메이션 적용에는 문제없을거에용~!
근데 중요한 부분은 아닌듯해서 그대로 놔둬도 괜찮을 것 같습니다~! 방식의 차이지용
 오히려 새로운 구성형태를 공부할 수 있어서 좋았어용~! 👍

2022-11-29 07:34 UTC, hs-ryu approved these changes
고생하셨습니다!

2022-11-29 07:34 UTC, merged