✨ 체크리스트를 코어데이터와 연결하고 CRUD 작업을 비동기 처리 하였습니다.
IIION/Workade pull request #14
Opened 2022-10-24 04:51 UTC by DevLuce

# 배경
- 체크리스트를 코어데이터로의 연동이 필요합니다.
- 체크리스트의 디테일뷰로 들어가서 나왔을 때의 비동기 처리가 필요합니다.
- 체크리스트이 CRUD가 필요합니다.

# 작업 내용
- CheckList 와 Todo 를 관계형으로 코어데이터 모델링
- CRUD 작업
- 데이터를 다루는 비즈니스 로직은 ViewModel로 분리
- 체크리스트 디테일뷰로 들어가서 삭제 및 편집 시에 체크리스트뷰에도 반영되는 비동기 작업을 NotificationCenter로 구현 

# 테스트 방법
- SceneDelegate에서 UINavigationController(rootViewController: CheckListViewController()) 로 테스트 가능합니다.

# 리뷰 노트
- 올바른 MVVM 패턴으로 구현한지 잘 모르겠습니다. 피드백 부탁드립니다.
- 제목을 길게 수정할 경우 벗어나는데 제한이 있으면 좋을 것 같습니다.
- Dynamic이 아닌 NotificationCenter로 비동기를 구현하였는데 같이 논의해보면 좋을 것 같습니다.

# 스크린샷

https://user-images.githubusercontent.com/56063805/197450611-0c911f65-6c14-43cd-8112-5f6e6ac24e5b.mov

2022-10-24 18:29 UTC, E-know requested changes
혁키 하나의 PR에 너무 많은 코드 줄이 올라오면 리뷰어가 지칩니다. 😢

코드 리뷰어를 배려해주세요. 

하나의 ViewController에 변수가 많아지면 

스크린샷에 명칭을 달아주면 리뷰어가 더 보기 편하다고 생각합니다.

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
> +    }
[P4] setup보다는 setupComponent 나 setupCell이 어떨까요?

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +    }()
[P3] dateLabel은 날짜를 알려 주는 label이라는 혼돈을 줄 수 있을 것 같습니다.

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +        button.addTarget(self, action: #selector(addButtonPressed(_:)), for: .touchUpInside)
[P4] 버튼에 대해서 어떤 공통된 UX를 줄지 고민해보면 좋을 것 같습니다.

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +}
[P1] 제목 글자가 계속 입력됩니다. 화면 밖으로 나가면 입력이 안되게 하거나 글자수를 제한해야 한다고 생각합니다.

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
> +//  CheckListDetailViewModel.swift
[P3] Coredata에 대한 부분은 Manager를 따로 만들어서 관리하는 것에 대해서 어떻게 생각하시나요??

2022-10-24 18:29 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListViewController.swift
> +    }
[P2] `편집` 뿐만 아니라 `완료`가 눌려졌을 때에도 데이터를 다루기에 barButtonPressed는 어떤가요?

2022-10-24 18:31 UTC, E-know commented
![스크린샷 2022-10-25 오전 3 29 53](https://user-images.githubusercontent.com/55151796/197599115-058dc3fa-9ad5-4dc6-8285-9d7def172a50.png)
어떤 CRUD를 다룬것인지 구체적으로 쓰면 좋을 것 같습니다.

2022-10-24 18:32 UTC, E-know commented
![스크린샷 2022-10-25 오전 3 31 50](https://user-images.githubusercontent.com/55151796/197599471-07df2ecc-fb95-440d-903b-bf15dce7ba0c.png)
어떤 부분에서 MVVM인지 헷갈린다고 생각하시나요??

2022-10-25 14:03 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
> +    }
넵 반영했습니다!

2022-10-25 14:06 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +    }()
반영하였습니다!

2022-10-25 14:10 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +        button.addTarget(self, action: #selector(addButtonPressed(_:)), for: .touchUpInside)
어떤 의미인지 이해를 못했습니다. 다시 상세하게 설명 가능할까요?

2022-10-25 14:12 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
> +//  CheckListDetailViewModel.swift
네. 저도 그 점에 대해서 인지하고 Core Data 매니저를 만들어 관리하려고 했으나 아직 역량 부족으로 어떻게 나눠야할지 고민해보고 있는 상황입니다. TODO로 등록해놓고 추후 분리하도록 하겠습니다.

2022-10-25 14:16 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListViewController.swift
> +    }
반영하였습니다!

2022-10-25 14:17 UTC, DevLuce commented
> 혁키 하나의 PR에 너무 많은 코드 줄이 올라오면 리뷰어가 지칩니다. 😢
> 
> 코드 리뷰어를 배려해주세요.
> 
> 하나의 ViewController에 변수가 많아지면
> 
> 스크린샷에 명칭을 달아주면 리뷰어가 더 보기 편하다고 생각합니다.

어떻게 명칭을 달아주면 되는지 예시 보여주실 수 있을까요?

2022-10-25 14:17 UTC, DevLuce commented
> ![스크린샷 2022-10-25 오전 3 29 53](https://user-images.githubusercontent.com/55151796/197599115-058dc3fa-9ad5-4dc6-8285-9d7def172a50.png) [P3]어떤 CRUD를 다룬것인지 구체적으로 쓰면 좋을 것 같습니다.

넵!

2022-10-25 14:19 UTC, DevLuce commented
> ![스크린샷 2022-10-25 오전 3 31 50](https://user-images.githubusercontent.com/55151796/197599471-07df2ecc-fb95-440d-903b-bf15dce7ba0c.png) [P3] 어떤 부분에서 MVVM인지 헷갈린다고 생각하시나요??

최대한 비즈니스 로직을 분리해서 ViewModel에 작성하려고 했는데 ViewController 에 그래도 비대한 코드량은 여전한 거 같아서 이게 제대로된 분리가 맞는지 헷갈렸습니다. 추후 멘토분들에게 멘토링을 받아보도록 하겠습니다.

2022-10-26 02:56 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +}
@eraser3031 이 부분에 대해서 코멘트로 기록을 남기면 좋을 것 같습니다! 글자수 넘어가는 문제입니다!

2022-10-26 02:58 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +        button.addTarget(self, action: #selector(addButtonPressed(_:)), for: .touchUpInside)
앗 제가 코멘트를 자세하게 달지 못했군요. 버튼에 대해서 작동방식이 조금 다른 상황입니다.
제 기억으로는 touchupInside / touchDown / touchUP 이렇게 다르게 버튼이 작동됨을 확인했습니다.
이건 UX측면이라 생각해서 조금 공통되게 가져갈 필요가 있다고 생각해서 남긴 코멘트였습니다.

2022-10-26 02:59 UTC, E-know commented
> > ![스크린샷 2022-10-25 오전 3 29 53](https://user-images.githubusercontent.com/55151796/197599115-058dc3fa-9ad5-4dc6-8285-9d7def172a50.png) [P3]어떤 CRUD를 다룬것인지 구체적으로 쓰면 좋을 것 같습니다.
> 
> 넵!
![197683141-9e2d90cf-fded-4ccc-aa10-89a00ebbfe69](https://user-images.githubusercontent.com/55151796/197924199-9ce6b9e9-5e94-4cbf-be14-1737ba268b3b.png)
제 PR에서 가져왔습니다. 제것보다 더 깔끔하게 할 수 있을것 같은데 저는 저의 똥손 이슈 때문에...ㅎㅎ

2022-10-26 03:00 UTC, E-know commented
> > 혁키 하나의 PR에 너무 많은 코드 줄이 올라오면 리뷰어가 지칩니다. 😢
> > 코드 리뷰어를 배려해주세요.
> > 하나의 ViewController에 변수가 많아지면
> > 스크린샷에 명칭을 달아주면 리뷰어가 더 보기 편하다고 생각합니다.
> 
> 어떻게 명칭을 달아주면 되는지 예시 보여주실 수 있을까요?

![197683141-9e2d90cf-fded-4ccc-aa10-89a00ebbfe69](https://user-images.githubusercontent.com/55151796/197924199-9ce6b9e9-5e94-4cbf-be14-1737ba268b3b.png)
제 PR에서 가져왔습니다. 제것보다 더 깔끔하게 할 수 있을것 같은데 저는 저의 똥손 이슈 때문에...ㅎㅎ

2022-10-26 04:46 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
> +}
[P1] 제목 글자수를 12자로 제한하자는 이야기가 저번 스크럼에 나왔었습니다. 반영 부탁드립니다. 또한 12글자를 제한하는 디자인을 에반이 봐주시기로 해주셨는데 답이 없군요 ㅠ

2022-10-26 05:35 UTC, E-know approved these changes

2022-10-26 05:36 UTC, merged