✨ 주변장소 / 갤러리 뷰를 완성했습니다.
IIION/Workade pull request #15
Opened 2022-10-24 11:47 UTC by eraser3031

# 배경
- 주변장소 모달에서 세그먼트 컨트롤로 들어가는 갤러리 뷰를 완성했습니다.
- GalleryViewController는 차후 빅썬과 합치는 과정에서 사라질 뷰컨트롤러이며 지금은 CollectionView의 델리게이트가 어떻게 구성되는 지 테스트 및 개발하기 위해 만들어졌습니다.
- GalleryDetailViewController는 사용자가 사진을 선택할 시 디테일하게 하나의 사진을 보여줍니다.
- 이미지 로딩의 경우 뷰모델만 따로 빼두고 우선 저작권 프리인 샘플 사진을 사용하고 있습니다. 

# 작업 내용
- 갤러리 뷰 UICollectionView로 구현
- Uiviewcontrolleranimatedtransitioning를 통해 디테일 화면 구현
- 핫픽스로 UIFont, 및 SubHeadline 스타일 변경

# 테스트 방법
- SceneDelegate에서 GalleryViewConroller를 rootViewController로 바꿔주시면 됩니다.

# 리뷰 노트
- 문법 및 디자인 반영 여부

# 스크린샷
<img width="300" alt="스크린샷 2022-10-19 오후 5 50 31" src="https://user-images.githubusercontent.com/63719961/197518381-757d5fea-7011-49be-a83d-a24b9ee36e01.gif">

2022-10-24 13:47 UTC, jeohong reviewed
[P3] IPhone 8, IPhone 14 Pro, IPhone 14 ProMax 세가지 기종에서 구동 확인 했습니다.
Return 전에 개행 추가만 부탁드려요!

2022-10-24 13:47 UTC, jeohong commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        return copy
[P3] return 전에 개행 추가 부탁드려요!

2022-10-24 13:47 UTC, jeohong commented on Workade/Views&ViewModels/Gallery/GalleryViewController.swift
> +        return true
[P3] 요기두!

2022-10-24 13:47 UTC, jeohong commented on Workade/Views&ViewModels/Gallery/UICollectionViewTwoLineLayout.swift
> +        return collectionView.bounds.width - (insets.left + insets.right)
[P3] 요기두!

2022-10-24 13:59 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        return copy
수정했습니다!! 세세한 리뷰 감사합니다!

2022-10-24 13:59 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/GalleryViewController.swift
> +        return true
수정완료했습니다!

2022-10-24 13:59 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/UICollectionViewTwoLineLayout.swift
> +        return collectionView.bounds.width - (insets.left + insets.right)
요기두 수정했습니다!

2022-10-25 07:43 UTC, E-know requested changes

2022-10-25 07:43 UTC, E-know commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        guard let item = galleryViewController.collectionView.cellForItem(at: indexPath!) as? GalleryCollectionViewCell else { return }
[P2] 강제 언래핑 금지!! guard를 사용해주세요!

2022-10-25 07:43 UTC, E-know commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        }
[P3] transition의 enum값이 2개이지만 switch나 else 문에 주석으로 else는 transition값이 어떤 값일 때 작동되는 것인지 써주면 좋을 것 같습니다.
```
if {
} else { // transition == .dismissal
}
```
이런 형식으로요.

2022-10-25 07:43 UTC, E-know commented on Workade/Views&ViewModels/Gallery/GalleryDetailViewController.swift
> +        let aspectR = (image?.size.width ?? 0) / (image?.size.height ?? 0)
[P1]`image.size.height`의 값을 못 찾으면 0을 사용하는데 0으로 나누면 에러 발생!

2022-10-25 07:43 UTC, E-know commented on Workade/Views&ViewModels/Gallery/GalleryDetailViewController.swift
> +    }
[P2] [스크럼에서 나온 내용](https://ilion-hq.slack.com/archives/C043PAH0P1U/p1666675588989419)에 따라서 객체마다 분리시켜 주세요.

2022-10-25 07:43 UTC, E-know commented on Workade/Views&ViewModels/Gallery/GalleryViewController.swift
> +class GalleryViewController: UIViewController, UICollectionViewDataSource, TwoLineLayoutDelegate {
[P3] 짜잘하더라도 delegate마다 분리 부탁드립니다.

2022-10-25 07:45 UTC, E-know commented
하나의 PR에 너무 많은 코드가 있어서 리뷰하기가 힘듭니다. ㅠㅠ 😢 

불가피하게 하나의 구현을 위해서 코드가 길어졌다면 어쩔 수 없지만 그렇지 않았더라면 PR을 분리해주세요.

또한 코드가 불가피하게 길어졌다면 스크린샷에서 하나씩 지명하는 스크린샷이 코드 리뷰어입장에서 좋습니다.

2022-10-25 08:21 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        guard let item = galleryViewController.collectionView.cellForItem(at: indexPath!) as? GalleryCollectionViewCell else { return }
반영했습니다!

2022-10-25 08:21 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
> +        }
저도 코드짤 때 해당 파트가 길어지면서 자꾸 헷갈리곤 했는데 좋은 방법인 것 같습니다!! 감사합니다!

2022-10-25 08:27 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/GalleryDetailViewController.swift
> +        let aspectR = (image?.size.width ?? 0) / (image?.size.height ?? 0)
```suggestion
        var aspectR: CGFloat = 1
        if let image = image {
            aspectR = image.size.width / image.size.height
        }
```
이미지가 nil이면 1대1 비율을 가지도록 수정했습니다!! 좋은 지적 감사드립니다!

2022-10-25 08:27 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/GalleryDetailViewController.swift
> +    }
반영했습니다!

2022-10-25 08:37 UTC, eraser3031 commented on Workade/Views&ViewModels/Gallery/GalleryViewController.swift
> +class GalleryViewController: UIViewController, UICollectionViewDataSource, TwoLineLayoutDelegate {
반영했습니다!

2022-10-25 08:39 UTC, eraser3031 commented
> 하나의 PR에 너무 많은 코드가 있어서 리뷰하기가 힘듭니다. ㅠㅠ 😢
> 
> 불가피하게 하나의 구현을 위해서 코드가 길어졌다면 어쩔 수 없지만 그렇지 않았더라면 PR을 분리해주세요.
> 
> 또한 코드가 불가피하게 길어졌다면 스크린샷에서 하나씩 지명하는 스크린샷이 코드 리뷰어입장에서 좋습니다.

다음부터는 주의해서 PR 올리도록 하겠습니다. 많은 코드 보시느라 고생 많으셨고 감사드립니다..😭
차후엔 주석과 더 자세하게 PR 내용을 작성하도록 하겠습니다!!

2022-10-25 11:20 UTC, E-know approved these changes

2022-10-25 11:20 UTC, merged