✨ TipItemDetailView 에 Scroll View를 적용하였습니다.
IIION/Workade pull request #18
Opened 2022-10-25 07:07 UTC by jeohong

# 배경
- TipDetailView 에서 Cell 클릭시 해당 Item의 View를 FullScreen으로 띄우고, 해당 뷰의 ScrollView 를 적용

# 작업 내용
- Extension을 통해 공통 사용되는 Close 버튼 생성
- ScrollView 적용

# 테스트 방법
- SceneDelegate에서 rootViewController 를 MagazineViewController로 적용후, 팁에서 아무 셀 눌러서 확인

# 리뷰 노트
- Close 버튼을 재사용 되게 구성 하였습니다 확인해주세요
- 스크롤 최상단에서 내릴때  상단에 고정되도록 하였습니다.

# 스크린샷
https://user-images.githubusercontent.com/96639917/197706110-84f54a01-f79b-4fcf-89d1-e25f0b32da18.mov

2022-10-25 08:28 UTC, E-know requested changes

2022-10-25 08:28 UTC, E-know commented on Workade/Views&ViewModels/Magazine/TipDetail/TipItemDetailViewController.swift
> +    var label: String?
[P2] 생성자로 반드시 받게끔 하는 것은 어떤가요??

2022-10-25 09:02 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipItemDetailViewController.swift
> +    var label: String?
반영하였습니다!

2022-10-26 04:51 UTC, E-know reviewed
변수명이 너무 많아지면... 스크린 샷에 같이 동봉해주시는면 리뷰어가 더 편하게 볼 수 있을것 같습니다.
![197683141-9e2d90cf-fded-4ccc-aa10-89a00ebbfe69](https://user-images.githubusercontent.com/55151796/197937441-5b07fa92-1dde-4897-9270-1d34bf331a0f.png)
제가 올린 PR의 예시입니다! 형식은 저것보다 이쁘게 하실 수 있으실 겁니다. ㅎㅎ 저는 똥손이라.

2022-10-26 04:51 UTC, E-know commented on Workade/Share/CustomNavigationBar.swift
> +    var rightButtonImage: UIImage?
[P3] private...???

2022-10-26 04:59 UTC, jeohong commented on Workade/Share/CustomNavigationBar.swift
> +    var rightButtonImage: UIImage?
오우.. 반영 하였습니다! 

스크린샷과 변수명의 경우 좋은거 같아요 추후 PR에서 반영하겠습니다!

2022-10-26 06:17 UTC, E-know commented
[P1] 컨플릭트 해결 부탁드려요!

2022-10-26 06:41 UTC, jeohong commented
> [P1] 컨플릭트 해결 부탁드려요!

해결했습니다 :)

2022-10-26 07:01 UTC, E-know approved these changes

2022-10-26 07:01 UTC, merged