✨Feat MagazineView 의 Custom TabBar 를 적용 하였습니다.
IIION/Workade pull request #2
Opened 2022-10-18 15:35 UTC by jeohong

# 배경
- 매거진 뷰의 커스텀 탭 바 적용

# 작업 내용
- StackView를 이용하여 4개의 버튼 ( 전체, 팁, 칼럼, 후기 ) 를 배치
- 구분선 적용
- 각 탭의 버튼을 누를때 각각의 View를 연동

# 테스트 방법
- 방법 1. sceneDelegate 의 rootView 를 MagazineViewController 로 수정후 실행하여 확인
- 방법 2. 프리뷰 코드를 MagazineViewController 아래에 추가하여 프리뷰로 확인

# 리뷰 노트
- 각 탭의 View의 상세 내용은 아직 적용되지 않았습니다.
- 선행 View인 HomeView에서 Navigation이 적용되기 전이기 때문에 Hi-fi에 있는 뒤로가기 버튼은 아직 적용 전 입니다.
- CustomTabBar는 각각의 버튼으로 구성되었습니다.
- 전체 배경색상을 SceneDelegate에서 적용하면 좋을것 같습니다.
- 상세 색상은 Color Extention이 적용된후 수정하겠습니다.
- 각 탭의 DetailView의 label 변수명이 testLabel 입니다. View 를 수정할때 삭제될 내용이기에 그대로 Commit 올립니다!

# 스크린샷
<img width="300" alt="image" src="https://user-images.githubusercontent.com/96639917/196476816-b61217e4-e0b3-4599-830c-a90c2d95426e.png">

2022-10-18 16:20 UTC, BrightHyeon approved these changes

2022-10-18 16:20 UTC, BrightHyeon commented on Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
> +        return label
[p5] 이 사이 여백도 내일 이야기해보고 통일시키면 좋을 것 같아요!

2022-10-18 16:23 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
> +        return label
좋습니다 다음 회의때 이야기 나눠봐요!

2022-10-18 16:26 UTC, E-know requested changes
테스트 방법을 조금 더 구체화해서 적어주세요. 지금은 파란화면만 나옵니다. 어느 코드의 어디 부분을 수정하면 테스트 화면을 볼 수 있다 구체적으로 명시하면 좋을 것 같습니다.

2022-10-18 16:26 UTC, E-know commented on Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
> +    }()
[P2] 라벨 이름이 testLabel 이름인 이유가 궁금합니다.

2022-10-18 16:26 UTC, E-know commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    }()
[P1] Btn 대신에 코드 컨벤션을 위해서 Button 풀네임을 써주세요.

2022-10-18 16:26 UTC, E-know commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    }
[P2] View 한 개가 갖고 있는 요소가 많아지면 configureUI 함수가 너무 길어질 염려가 있을 것 같습니다. 다음 스크럼에서 다뤄보면 좋을것 같습니다.

2022-10-18 16:30 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
> +    }()
해당 내용은 리뷰노트에 적어 놓았습니다. 추후 컨텐츠 추가시 모두 삭제될 내용이기에 testLabel로 작성했습니다.

2022-10-18 16:30 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    }()
반영하겠습니다 :)

2022-10-18 16:33 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    }
다음 회의때 이야기 나눠봐요 좋습니다 :)

2022-10-19 03:19 UTC, hs-ryu reviewed
확인했습니다! 별다른 리뷰는 없습니다!

2022-10-20 06:28 UTC, E-know commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    func settingDetailView() {
```suggestion
    func setupDetailView() {
```
[P3] 문맥 통일성을 위해서 위와 같은 수정은 어떤가요?

2022-10-20 06:28 UTC, E-know commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    func settingStackView() {
```suggestion
    func setupStackView() {
```
[P3] 문맥 통일성을 위해서 위와 같은 수정은 어떤가요?

2022-10-20 06:32 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    func settingDetailView() {
반영하였습니다 👍

2022-10-20 06:32 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +    func settingStackView() {
반영하였습니다 👍

2022-10-20 06:54 UTC, E-know commented
컨플릭트 해결 부탁드립니다!

2022-10-20 07:42 UTC, E-know approved these changes

2022-10-20 07:42 UTC, merged