✨ EmojiPickerController를 추가했습니다.
IIION/Workade pull request #26
Opened 2022-10-26 11:22 UTC by eraser3031

# 배경
- 체크리스트 뷰에서 각 체크리스트가 지니고 있는 이모지를 선택하기 위한 EmojiPickerViewController를 추가했습니다.

# 작업 내용
- 체크리스트에 사용될 EmojiPickerViewController 추가

# 테스트 방법
ViewController에 
```
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        present(UINavigationController(rootViewController: EmojiPickerViewController()), animated: true)
    }
```
를 추가해주시고 SceneDelegate에서 rootViewController를 ViewController로 바꿔주신 뒤 실행시켜 이모지 클릭 시 콘솔에 해당 이모지가 잘 출력되는 지 확인해주세요

# 리뷰 노트
- 코드 리뷰어가 이 리뷰에 대해서 자세하게 봐줬으면 하는 것들
- 이 PR을 작성하면서 참고했던 사이트들

# 스크린샷
![emoji](https://user-images.githubusercontent.com/63719961/198013720-803218a9-f4a3-4702-a51d-9ad2d7404234.gif)

2022-10-26 13:19 UTC, eraser3031 commented
> # 배경
> * 체크리스트 뷰에서 각 체크리스트가 지니고 있는 이모지를 선택하기 위한 EmojiPickerViewController를 추가했습니다.
> 
> # 작업 내용
> * 체크리스트에 사용될 EmojiPickerViewController 추가
> 
> # 테스트 방법
> ViewController에
> 
> ```
>     override func viewDidAppear(_ animated: Bool) {
>         super.viewDidAppear(animated)
>         present(UINavigationController(rootViewController: EmojiPickerViewController()), animated: true)
>     }
> ```
> 
> 를 추가해주시고 SceneDelegate에서 rootViewController를 ViewController로 바꿔주신 뒤 실행시켜 이모지 클릭 시 콘솔에 해당 이모지가 잘 출력되는 지 확인해주세요
> 
> # 리뷰 노트
> * 레이아웃 깨지는 지 여부
> * 문법 및 리펙토링 필요 사항
> 
> # 스크린샷
> ![emoji](https://user-images.githubusercontent.com/63719961/198013720-803218a9-f4a3-4702-a51d-9ad2d7404234.gif) [ ![emoji](https://user-images.githubusercontent.com/63719961/198013720-803218a9-f4a3-4702-a51d-9ad2d7404234.gif) ](https://user-images.githubusercontent.com/63719961/198013720-803218a9-f4a3-4702-a51d-9ad2d7404234.gif) [ ](https://user-images.githubusercontent.com/63719961/198013720-803218a9-f4a3-4702-a51d-9ad2d7404234.gif)

2022-10-26 13:22 UTC, eraser3031 commented
테스트 방법을 수정했습니다!

2022-10-26 14:12 UTC, jeohong reviewed
[P3] 확인했습니다 수고하셨어용!

2022-10-26 14:12 UTC, jeohong commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +
[P3] 잡았다 요놈! 공백 삭제 부탁드립니당

2022-10-26 14:20 UTC, BrightHyeon commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +        self.navigationController?.navigationBar.tintColor = .theme.quaternary
[P3] navigationBar 속성의 경우, 다른 스택으로 이동 시 해당 컨트롤러의 네브바 속성도 그대로 변경시키는 걸로 압니다! 확인 후, 뷰가 사라지는 시점에 설정을 원점으로 돌리면 좋을 것 같습니다.

2022-10-26 14:25 UTC, hs-ryu commented
확인했습니다.

2022-10-26 14:39 UTC, eraser3031 commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +
수정했습니다!!

2022-10-26 14:42 UTC, eraser3031 commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +        self.navigationController?.navigationBar.tintColor = .theme.quaternary
> [P3] navigationBar 속성의 경우, 다른 스택으로 이동 시 해당 컨트롤러의 네브바 속성도 그대로 변경시키는 걸로 압니다! 확인 후, 뷰가 사라지는 시점에 설정을 원점으로 돌리면 좋을 것 같습니다.

```
override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.navigationBar.tintColor = .theme.primary
}
```
을 추가했습니다!! 좋은 지적 감사드립니다!

2022-10-26 18:36 UTC, E-know requested changes
이모지픽커를 분리시킬 수 있으면 더 분리해서 깔끔한 코드가 될 수 있지 않을까 싶습니다!
이건 다같이 고민해봐요. 저도 차선책이 있을 것 같은데 라는 막연한 생각입니다!

2022-10-26 18:36 UTC, E-know commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +    }
[P1] enum은 모델쪽에 구현되어야 한다고 생각합니다. 안에 선언하신 이유가 있나요?

2022-10-26 19:15 UTC, eraser3031 commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +    }
UICollectionView에서 DiffableDataSource를 사용할 때 Section 분리 용도로만 사용되기 때문에 저는 내부에 선언되는 게 맞다고 생각했습니다! 차후에 다른 DiffableDataSource를 사용하는 UICollectionView들이 추가된다면NSDiffableDataSourceSnapshot<EmojiPickerSection, String>같이 사용해서 구분할 수 있기야 하겠지만 가독성이 떨어지고 앞서 말씀드린 것 처럼 해당 VC 내부에서만 사용되는 내부에서만 사용되기 때문에 모델보다는 뷰의 일부에 가깝다고 생각이 듭니다!

2022-10-26 19:20 UTC, eraser3031 commented on Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
> +    }
SwiftUI의 경우에도 @Published 프로퍼티를 지닌 뷰모델을 사용해서 모델과 뷰 사이 데이터 바인딩을 구현하지만 모델과 별개로 뷰를 특정 상태에서 변화시켜줘야하는 상황(e.g. 단순 시각적 효과를 위한 애니메이션)을 참작해 뷰 내부에 선언하여 사용되는 @State가 존재하는 것처럼 Section 또한 예외로 모델로 빼주지 않아도 될 것 같다는 생각입니다.

2022-10-27 12:56 UTC, E-know approved these changes

2022-10-27 12:56 UTC, merged