✨ 주변 장소 뷰에서 데이터 로드, 스크롤 뷰, 네비게이션 바 구현 완료 했습니다.
IIION/Workade pull request #27
Opened 2022-10-26 14:22 UTC by hs-ryu

# 배경
- 주변 장소 뷰에서 스크롤에 따른 효과들을 구분해야합니다.
- 네비게이션 바가 필요합니다.

# 작업 내용
- 전체 스크롤 뷰 안에 디테일 부분의 스크롤 뷰를 구현했습니다. 세그먼트 컨트롤로 전체 스크롤 뷰의 active 상태를 변경해야 하기 때문에, 스크롤을 2개로 구분하여 작성하였습니다.
- 네비게이션 바는 임시 뷰로 작성했습니다. 머지 이후, 치콩이 작성한 코드로 수정 예정입니다. 관련하여 TODO 주석으로 작성했습니다.
- 네비게이션이 안떴을때 dismiss 버튼 역시 임시로 작성해 놓았습니다. 마찬가지로 치콩이 컴포넌트로 빼놨기 때문에 머지 이후 변경하겠습니다.
- json으로부터 데이터를 로드하는 로직을 작성했습니다. 이후 URL 세션으로 json 파일을 불러와 세팅하는 작업을 할 예정입니다.

# 테스트 방법
- scene delegate에서 루트뷰를 window?.rootViewController = UINavigationController(rootViewController: NearbyPlaceViewController()) 로 변경 후 진행합니다.

# 리뷰 노트
- 코드 정리에 미숙하여 네비게이션 바를 제외한 모든 컴포넌틀을 한 뷰에 작성했기 때문에 읽기 불편하게 만든 점 미리 죄송합니다. 이번 스프린트 이후 리팩토링 철저하게 하도록 하겠습니다.

# 스크린샷
- 직접 테스트 해보며 확인해 보시길 추천드립니다!
|
<img width="250" alt="image" src="https://user-images.githubusercontent.com/75309495/198051759-a3fb3217-be38-46cc-a7ea-cf90569d9835.png">
|
<img width="582" alt="image" src="https://user-images.githubusercontent.com/75309495/198051890-139d721b-8e0f-4f82-9a53-9f4db1ee6c34.png">
|

2022-10-26 18:41 UTC, E-know requested changes

2022-10-26 18:41 UTC, E-know commented on Workade/Dummies/NearbyPlaceViewDetailData.json
> +}
[P1] 더미 데이터는 이제 제거해주세요!

2022-10-26 18:41 UTC, E-know commented on Workade/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: NearbyPlaceViewController())
[P2] SeneDelegate 검지검지!

2022-10-26 18:41 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +        }
[P4] 콜백보다는 await를 하는 방향으로 하고 싶은데 나중에 매니저를 만들면 수정하면 되니 주석 달면 좋을 것 같습니다!

2022-10-26 18:41 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +//        view = nearbyPlaceView
[P3] 필요 없는 주석!!

2022-10-26 19:37 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +//        view = nearbyPlaceView
놓쳤네요 ㅠ. 확인해 주셔서 감사합니다. 바로 반영했습니다

2022-10-26 19:43 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +        }
TODO로 주석 작성 후 다시 올렸습니다 :D

2022-10-26 19:44 UTC, hs-ryu commented on Workade/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: NearbyPlaceViewController())
죄송죄송!

2022-10-26 19:44 UTC, hs-ryu commented on Workade/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: NearbyPlaceViewController())
수정하였읍니다.

2022-10-26 19:45 UTC, hs-ryu commented on Workade/Dummies/NearbyPlaceViewDetailData.json
> +}
더미 데이터 제거 했습니다. 현재는 더미 json에서 들고 오고 있기 때문에 detail 정보가 표시되지 않을 수 있습니다.

2022-10-26 20:40 UTC, hs-ryu commented
확인후 어싸인 해주시면 컨플릭 잡도록 하겠습니다!

2022-10-27 12:27 UTC, E-know approved these changes

2022-10-27 12:27 UTC, merged