♻️ 스프린트 1에서 기획된 체크리스트 템플릿 추가 기능을 완료하였습니다.
IIION/Workade pull request #50
Opened 2022-11-03 06:41 UTC by DevLuce

# 배경
- 체크리스트 템플릿을 셀에서 바로 추가할 수 있도록 합니다.
- 체크리스트 템플릿의 목록을 확인하고 모달에서 추가할 수 있도록 합니다.

# 작업 내용
- 체크리스트를 생성할 때의 업데이트 오류를 수정하였습니다.
- 체크리스트 관련 코드를 NetworkManager와 Model 관련 디렉토리로 이동하여 리팩토링 하였습니다.
- hexStringToColor 코드를 UIColor+ 에 추가하였습니다.
- 체크리스트 템플릿 셀의 이미지 패딩값을 추가하였습니다.
- 체크리스트 템플릿을 셀과 모달에서 모두 추가할 수 있도록 구현하였습니다.

# 테스트 방법
- 앱을 실행하여 홈화면에서 체크리스트로 들어가면 됩니다.

# 스크린샷

https://user-images.githubusercontent.com/56063805/199660692-70a8a8ff-e23f-403a-ac1a-7097b4e14630.mov

2022-11-03 07:01 UTC, E-know commented
<img src="https://user-images.githubusercontent.com/55151796/199663077-43f800eb-49f4-49b1-8bf2-e3cb38629fca.PNG" height=300>
[P2] 하단에 추가되는 체크리스트들의 불러오는 이미지(위 이미지)에서 스크롤을 막아두신 이유가 궁금합니다!

2022-11-03 07:07 UTC, DevLuce commented
> <img alt="" height="300" src="https://user-images.githubusercontent.com/55151796/199663077-43f800eb-49f4-49b1-8bf2-e3cb38629fca.PNG">
> 
> [P2] 하단에 추가되는 체크리스트들의 불러오는 뷰에서(위 이미지)에서 스크롤을 막아두신 이유가 궁금합니다!

양쪽 끝을 안쪽으로 둥글게 만드느라 투명한 뷰가 덮어져 있습니다. 제 수준으로는 그렇게 구현하였는데 해결 가능한지 더 알아보겠습니다.

2022-11-03 07:13 UTC, E-know requested changes

2022-11-03 07:13 UTC, E-know commented on Workade/Managers/NetworkManager.swift
> +    func fetchCheckListTemplateData<T: Codable>() async throws -> T {
```suggestion
    func requestCheckListTemplateData<T: Codable>() async throws -> T {
```
[P2] 문맥상 항상 갖고 올 수 있는 데이터는 아니니 fetch보다는 request가 맞다고 생각됩니다!

2022-11-03 07:13 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewController.swift
> +        }
[의견] 오 코드가 길어져서 쪼겠군요! 한결 보기 편한 것 같습니다! 👍

2022-11-03 07:13 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
[P1] 👀

2022-11-03 07:18 UTC, DevLuce commented on Workade/Managers/NetworkManager.swift
> +    func fetchCheckListTemplateData<T: Codable>() async throws -> T {
아하 네! 그렇게 적용하겠습니다!

2022-11-03 12:54 UTC, hs-ryu commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewModel.swift
> +            checkListTemplateResource = try await NetworkManager.shared.fetchCheckListTemplateData()
<img width="300" alt="스크린샷 2022-11-03 오후 9 53 02" src="https://user-images.githubusercontent.com/75309495/199725609-6b2b05b8-c6fc-4a33-afd6-886d9a964249.png">

[P1] 브랜치를 압축 파일로 내려받아 실행해 보니, 이 부분에서 에러가 납니다. 체크 한번 부탁드려도 괜찮을까요?

2022-11-04 00:46 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewModel.swift
> +            checkListTemplateResource = try await NetworkManager.shared.fetchCheckListTemplateData()
앗 토비 리뷰에 의해 변경한 함수명을 정작 매니저 내에 이름을 안바꾸었군요!! 죄송합니다;;; 반영하였습니당~ 감사링

2022-11-04 03:05 UTC, jeohong reviewed
[P2] 확인했습니다. 토비의 리뷰대로 추가 후, 스크롤이 안되는데 여백을 터치한 후 아래 커스텀 모달이 내려가면서 스크롤이 되더라구요 

추가버튼을 누름과 동시에 아래 모달을 내려주면 뭔가 깔끔해 보일거 같은데 어떻게 생각하시나요?

유저 입장에서 스크롤이 바로 안되니까 앱이 멈춘것처럼 느껴집니다!

2022-11-08 05:35 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
>  import SwiftUI
[P2] SwiftUI 속에 UIKit 포함되어 있습니다 중복을 피해주세요!

2022-11-08 05:35 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
>      }
[P3] add 보다는 어떤 것을 더하는 것인지 이름을 알려주면 좋을 것 같습니다.

2022-11-08 05:48 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
>      }
어떤 템플릿 내용을 더하는 건데..
addTemplateContents 라고 하면 괜찮을까요?

2022-11-08 06:33 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
[P1] 앗 제가 적다가 말았군요. add 라는 함수가 한 줄 코드인데 addTemplate()를 직접 호출하는 것은 어떨까요?

2022-11-08 06:34 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
>      }
너무 좋은 것 같습니다!

2022-11-08 06:42 UTC, BrightHyeon reviewed
수고하셨습니당~!

2022-11-08 06:42 UTC, BrightHyeon commented on Workade/Extentions/UIColor+.swift
> +        if cString.hasPrefix("#") {
[p2] 이미 0xBBBBBB 형태의 hex Int를 받아서 처리하는 rgb 메서드가 있어서 전달인자 타입이 다르긴하나 통일해도 될 것이라 생각이 듭니다. 혹시 이 메서드가 같은 역할을 하는 메서드라면용!

2022-11-08 06:46 UTC, DevLuce commented on Workade/Extentions/UIColor+.swift
> +        if cString.hasPrefix("#") {
네! 같은 역할을 하는 메서드 맞습니다! 근데 서버에서 hex 문자열 형태로 받게 되는데 이게 #이 들어간 문자열인지 #없이 hex값만 있는 문자열일지 알 수 없어서 넣었습니다!! 어떻게 통일하는게 괜찮을까요?

2022-11-08 07:21 UTC, eraser3031 reviewed
확인했습니다!!

2022-11-08 07:28 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
add 함수는 object-c 함수로 버튼 액션으로 호출되는 코드이고 addTemplate 함수는 이전 뷰컨트롤러에서 인자로 넘겨주는 함수라서 이렇게 작성되었습니다! 더 깔끔하게 개선할 방법이 있을까요?

2022-11-08 07:43 UTC, BrightHyeon commented on Workade/Extentions/UIColor+.swift
> +        if cString.hasPrefix("#") {
아! 그렇군요 현재 저희 프로젝트에서 rgb메서드는 안쓰고 있고, DB에서는 문자열로 hex값을 주는군요! rgb메서드를 제거하고 지금 이 hexStringToUIColor 메서드 하나로 통일하기로하죵!

2022-11-08 07:43 UTC, BrightHyeon approved these changes
확인했습니다!

2022-11-08 08:22 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
```
button.setImage(xmarkImage, for: .normal)
        button.tintColor = .theme.primary
        button.layer.cornerRadius = 16
        button.insertSubview(blur, at: 0)
        button.addAction(UIAction(handler: { [weak self] _ in
            guard let addTemplate = self?.addTemplate else { return }
            addTemplate()
        }), for: .touchUpInside)
```
24-31 번째 줄을 다음과 같이 짜면 어떨까요?

2022-11-08 08:29 UTC, DevLuce commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
오우 가독성이 저해되는 느낌인데요...? 다른분들 의견도 들어보고 반영하겠습니다!

2022-11-08 08:37 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
확실히 가독성은 안 좋아지긴 하는군요. 메모리냐 가독성이냐 둘 중 하나군요.

2022-11-09 07:05 UTC, E-know commented on Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
> +    }
https://github.com/IIION/Workade/issues/60#issue-1441526745
Issue Tracking 완료!

2022-11-09 07:06 UTC, E-know approved these changes

2022-11-09 07:06 UTC, merged