✨ GalleryView에 Pagination 기능을 추가했습니다.
IIION/Workade pull request #55
Opened 2022-11-03 08:27 UTC by eraser3031

# 배경
- 오피스 상세 뷰에서 갤러리뷰를 띄워줄 때 네트워크 환경이 좋지 않은 경우 빈 화면이 나와 좋지 않은 사용자 경험을 주기 때문에 이를 개선하고자 무한스크롤(페이지네이션) 기능을 갤러리 뷰의 collectionView에 추가시켰습니다.

# 작업 내용
- GalleryViewModel 리팩토링
- GalleryView 내부 UICollectionView를 페이지네이션이 가능하도록 수정

# 테스트 방법
- 갤러리 뷰에서 빠르게 스크롤해 10개 단위마다 이미지를 새로 불러오는 것을 확인해주세요. (바나나오피스가 더 이미지 개수가 많아 테스트하기에 용이합니다. 가능하다면 인터넷 환경이 좋지못한 곳에서 해주면 좋습니다.)

# 리뷰 노트
- 문법 및 오탈자
- 차후에 생길 수 있는 버그 여부

# 스크린샷
https://user-images.githubusercontent.com/63719961/199675630-5bc674f3-94f4-4ff9-9763-f165ffd1872d.mp4

2022-11-04 01:53 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    private(set) var images: [UIImage] = []
[P5] 그냥 궁금한건데, private(set) 이 문법은 어떨때 쓰는 문법일까요??

2022-11-04 02:55 UTC, DevLuce reviewed
굳 고생하셨습니당

2022-11-04 02:55 UTC, DevLuce commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +                let selectedItem = collectionView.indexPathsForSelectedItems
[P3] 이 변수는 사용되지 않았는데 추후 사용 목적이 있을까요?

2022-11-04 03:10 UTC, jeohong reviewed
[P5] 고생하셨습니다 에반!

2022-11-04 03:10 UTC, jeohong commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    private(set) var images: [UIImage] = []
저도 이부분 궁금합니다!

2022-11-04 03:10 UTC, jeohong commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    init() { }
[P5] init 에 아무 동작도 하지 않는것 같은데 사용목적이 따로 있는건가요?

2022-11-04 03:10 UTC, jeohong commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +        else { return }
[P5] Gaurd let 구문을 상수별로 내려쓰기 해서 가독성이 좋네요!

2022-11-04 06:39 UTC, BrightHyeon commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    private(set) var images: [UIImage] = []
[p5] 읽기전용으로 구현됩니다! setter 기능만 private하게 둔다는 것이지용 (feat. 지나가던 탐나)

2022-11-04 06:52 UTC, BrightHyeon commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    private(set) var images: [UIImage] = []
private var isLoad = false // 내부에서는 수정 가능.
    
var isLoading: Bool { // 외부에서 접근용
    return isLoad
}

위에 이런 구현과 동일한 역할일 겁니당!

2022-11-04 08:20 UTC, BrightHyeon commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +            images.count < content.items.count
[p5] images.count < content.items.count 대신 사용하려고 isCanLoaded 프로퍼티를 그대로 활용하지않은 것은 혹시 어떤 점에서인가용~?

2022-11-04 08:20 UTC, BrightHyeon commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +            let paginationEndPoint = min(images.count + paginationUnit, content.items.count)
[p5] 오 이렇게 한 곳에서만 쓰는 값일지라도 paginationUnit이란 변수를 만들어줘서 명시적으로 나타내는 방법도 좋군용

2022-11-04 08:44 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +                let selectedItem = collectionView.indexPathsForSelectedItems
리팩토링의 잔재네요. 지워버리겠습니다!

2022-11-04 08:44 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +            images.count < content.items.count
헉.. 다른 곳에서도 쓰일 것 같아 따로 프로퍼티로 빼놨는데 정작 원래 쓰려던 곳은 반영을 안해놨네용.. 수정하겠습니다!!

2022-11-04 08:44 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    init() { }
무의식적으로 init이니까 살려야지~ 이렇게 생각했던 것 같네요.. 따로 사용 목적이 없어서 바로 반영하겠습니다!

2022-11-04 08:56 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +    private(set) var images: [UIImage] = []
탐나가 설명해주신 것처럼 프로퍼티에 대해 수정하려는 접근만 private해주는 기능이라 MVVM에서 뷰는 모델을 직접 수정해선 안되고 뷰모델을 거쳐야만 하기 때문에 private(set)이 사용되기에 적합한 상황인 것 같아 활용했습니다!

2022-11-04 09:17 UTC, BrightHyeon commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +            let paginationEndPoint = min(images.count + paginationUnit, content.items.count)
[p5] 전체적으로 아주 나이스코드👍 많이 배웁니당

2022-11-09 06:18 UTC, E-know requested changes

2022-11-09 06:18 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +                    return await self.manager.request(url: url)
[P1] 강한참조가 일어나지 않을까 싶습니다.

2022-11-09 06:18 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +        self.galleryVM = GalleryViewModel()
[P2] 줄인말 검지검지

2022-11-09 06:18 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +            }
[P1] 강한 참조 부분이 아닐까 생각됩니다.

2022-11-09 06:45 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
> +                    return await self.manager.request(url: url)
Task의 경우 DispatchQueue.main.asyncAfter와 같이 특정 시점에서 비동기작업이 진행됨이 보장되고 끝날 경우 참조를 해제한다고 알고 있기 때문에 weak self를 사용하지 않았는데 구글링을 해보니 Task 또한 작업 도중 뷰가 dismiss되면 메모리 누수가 날 수 있다는 걸 확인해서 반영하도록 하겠습니다!!

2022-11-09 06:45 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +            }
반영했습니다!

2022-11-09 06:48 UTC, eraser3031 commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +        self.galleryVM = GalleryViewModel()
galleryViewModel로 변경했습니다!

2022-11-09 06:55 UTC, E-know approved these changes

2022-11-09 06:55 UTC, merged