✨ 주변 장소 뷰에서 필요한 세그먼트 컨트롤을 구현했습니다.
IIION/Workade pull request #6
Opened 2022-10-20 13:39 UTC by hs-ryu

# 배경
- 주변 장소 뷰에서 소개, 갤러리 뷰를 나누기 위해 세그먼트 컨트롤이 필요합니다.

# 작업 내용
- 주변 장소 뷰에서 커스텀 세그먼트 컨트롤러 구현했습니다.
- 갤러리는 에반이 작업할 부분이라, 세그먼트 컨트롤 구현을 위해 임시로 TempGalleryView라는 파일을 만들어 진행했습니다. 에반 작업 이후 연결할 예정입니다. 관련하여 TODO로 주석 작성하였습니다.
- 각 세그먼트에 해당하는 뷰는 IntroduceView와 TempGalleryView로 따로 파일을 빼서 작업했습니다. 각 뷰에 해당하는 코드는 아직 작성하지 않았습니다.
- 폰트 및 컬러 통일은 추후 작업하겠습니다.

# 테스트 방법
- SceneDelegate에서 루트뷰 컨트롤러를 NearbyPlaceViewController로 변경후 실행하면 됩니다.
- window?.rootViewController = NearbyPlaceViewController()

# 리뷰 노트
- 세그먼트 컨트롤러는 뷰 2개를 쌓아놓고, selected 되면 alpha값을 1과 0으로 줘서 보여주는 방식으로 진행됩니다. 혹시 더 좋은 방법이 있다면 말씀해 주시면 감사하겠습니다. 아래 링크를 참고하여 작성했습니다.
- [Switch between container views using segmented control](https://www.youtube.com/watch?v=A6vxDDAUj2o&t=608s)
- 세그먼트 컨트롤러의 크기를 heightAnchor를 사용하여 잡았는데, 이 방법 말고 다른 방법이 있다면 알려주시면 감사드리겠습니다.
 
# 스크린샷
<img width="300" alt="image" src="https://user-images.githubusercontent.com/75309495/196963688-91f86180-25b1-4a76-be7c-f0681798c611.png">

2022-10-20 14:18 UTC, E-know commented
라벨과 Assignees를 붙여주세요!

2022-10-20 14:25 UTC, hs-ryu commented
> 다음에는 라벨과 Assignees를 붙여주세요!

2022-10-20 14:33 UTC, E-know commented
<img src="https://user-images.githubusercontent.com/55151796/196977671-113fb3de-3f18-459d-b758-bd54009669e0.png" height=150>
<img src="https://user-images.githubusercontent.com/55151796/196977786-0edd99f3-da37-4596-a8fd-164ea4c425f7.png" height=150>

[P1] 위 두개의 사진을 보면 피그마와 구현이 서로 다른것 같습니다! 수정 부탁드립니다.

2022-10-20 14:35 UTC, E-know requested changes

2022-10-20 14:35 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +                                                for: .normal)
[P2] 색상과 폰트는 merge 이후에 트래킹해야하는 issue를 남겨주세요!

2022-10-20 14:35 UTC, E-know commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +    }
[P3] 하나의 함수에서 동시에 작업하는 느낌이 듭니다. background와 Divider를 제거하는 함수 분리는 어떤가요?

2022-10-20 15:16 UTC, DevLuce commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +    let testLabel: UILabel = {
[P2] private 으로 선언하면 좋을것 같아요~

2022-10-20 15:16 UTC, DevLuce commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +        return label
[P1] 개행 넣어주십쇼

2022-10-20 15:16 UTC, DevLuce commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +class NearbyPlaceViewController: UIViewController {
~[P5] Nearby와 인연이 많으시군요~

2022-10-20 15:16 UTC, DevLuce commented on Workade/Views&ViewModels/NearbyPlace/TempGalleryView.swift
> +        return label
[P2] 임시 뷰라도 컨벤션은 지켜주세요~

2022-10-20 17:58 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +                                                for: .normal)
확인했습니다! TODO로 처리하고, 머지 이후 바로 반영하겠습니다

2022-10-20 18:05 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
> +    }
![image](https://user-images.githubusercontent.com/75309495/197024646-5658d653-b166-451f-ad1f-66b0792beb7d.png)

위와 같이 분리해 봤는데, 별로 좋은 방법이 아닌것 같아 조언을 구하고 싶습니다.

2022-10-20 18:09 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +    let testLabel: UILabel = {
오오 감사합니다! 추후 없어질 코드긴하지만, 신경쓰도록 하겠습니다!

2022-10-20 18:09 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
> +        return label
넵! 넣어서 커밋 다시 올렸습니다!

2022-10-20 18:10 UTC, hs-ryu commented on Workade/Views&ViewModels/NearbyPlace/TempGalleryView.swift
> +        return label
수정하여 올렸습니다! 좀 더 신경쓰도록 하겠습니다!

2022-10-21 00:35 UTC, DevLuce reviewed
전 확인완료!

2022-10-21 04:04 UTC, jeohong approved these changes
앞선 리뷰어들이 리뷰를 달아 주셨네요 
LGTM 🎉

2022-10-21 06:04 UTC, E-know approved these changes

2022-10-21 06:04 UTC, merged