Feat/map info
IIION/Workade pull request #74
Opened 2022-11-16 13:35 UTC by E-know

# 배경
- 네이버지도에서 마커를 클릭했을시에 밑에 정보와 네이버지도 링크가 필요합니다.

# 작업 내용
- 네이버지도위에 표시된 마커를 누르면 밑에 정보 창이 뜹니다.

# 테스트 방법
- 네이버지도에서 마커를 클릭하면 됩니다.

# 스크린샷
<img src="https://user-images.githubusercontent.com/55151796/202194597-e1e38d38-5f36-4fb4-85c5-07cb9106306a.jp" height=300>

2022-11-16 14:00 UTC, hs-ryu approved these changes

2022-11-16 14:00 UTC, hs-ryu commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +    }()
[P5] 여기 두 부분 혹시 그냥 var로 선언하신 이유가 있으실까요? 토비가 작성하신 MapViewController 에서는 private var로 요소들을 선언해서 쓰시는데, 여기도 private 붙여봐도 딱히 에러는 안나더라구요. 그리고 혹시 let으로 안쓰시는 이유가 있나요? 이건 그냥 궁금해서요

2022-11-16 14:33 UTC, jeohong requested changes
수고하셨습니다 토비! 
PR 제목 컨벤션에 맞게 변경해 주시면 좋을것같아요!

2022-11-16 14:33 UTC, jeohong commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +    var titleLabel: UILabel = {
[P2] var 로 선언한 특별한 이유가 있을까요 ?
UI컴포넌트의 경우 let 으로 할당해도 해당 컴포넌트의 특성 ( color, text 등등.. ) 을 수정할수 있고, var 를 사용하는것 보다 추후 해당 UILabel 자체가 변하지 않을거라면 let 으로 설정하는게 더 좋아 보이는데 

토비 의견은 어떤가요 👀?

2022-11-16 14:33 UTC, jeohong commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        return title
[P3] return전 공백 부탁드려요! 👏

2022-11-16 14:33 UTC, jeohong commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        return imageView
[P3] return전 공백 부탁드려요! 👏

2022-11-16 14:33 UTC, jeohong commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        ])
[P1] Figma상의 Hug로 되어있기 때문에 유동적으로 변해야 하는게 맞는것 같습니다! 
leading 과 trailing을 85씩만 할당하면 기기 너비와 상관없이 유동적으로 양쪽 모두 85만큼만 떨어진 상태로 titleLabel의 너비가 동적으로 변할것 같아요! 

200 고정값 + 85를 하게되면 기기별 대응에서 취약할수 있을것 같습니다!

```suggestion
        NSLayoutConstraint.activate([
            titleLabel.topAnchor.constraint(equalTo: self.topAnchor, constant: 22),
            titleLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -22),
            titleLabel.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 85),
            titleLabel.trailingAnchor.constraint(equalTo: self.leadingAnchor, constant: 85)
        ])
```

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +    }
[P2] Figma 상의 디자인을 보면 0.5mm의 stroke이 있는듯해서 이를 적용해야할 것 같고, MapInfoView 가장자리에 옅은 쉐도우도 있는 것 같아서 Figma확인 후 적용하면 좋을듯 합니다.

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +class MapInfoView: UIView {
[P3] 다른 클래스의 슈퍼클래스로 사용되고 있는 것이 아니라면 static dispatch를 위해 final 키워드를 붙이는 것은 어떤가요~?

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        setLayout()
[P4] 저희 초반에 이야기한대로 setupLayout()은 어떠신가용~?

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        mapButton.addAction(UIAction(title: "Go") { [weak self] _ in
[P5] 순수 호기심입니다! title을 "Go"로 설정하면, 어떤 면에서 활용이 가능한가용??

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +            markerImage.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 16)
[P2] 16 + 42 방식보단 widthAnchor로 잡는 것이 다른 사람이 볼 때 빠르게 이해하기 좋을 것 같습니다. 그리고 현재 top, bottom을 22씩 설정해서 height를 비율적으로 잡고있는데, width의 경우 42라는 고정값이 있어서 추후 MarkerInfoView의 height가 디자인상으로 변경되었을 때, 추가작업이 발생하게 될 듯합니다. 
```suggestion
            markerImage.widthAnchor
                .constraint(equalTo: markerImage.heightAnchor),
            markerImage.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 16)
```
변화에 유연하도록 이렇게 height와 일치시키는 방식은 어떠신가요?

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +            mapButton.leadingAnchor.constraint(equalTo: self.trailingAnchor, constant: -(16 + 42)),
[P2] 이전 markerImage의 레이아웃에 대한 의견과 동일한 의견입니다.

2022-11-16 14:34 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapViewController.swift
> +            markerInfoView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -96),
[P2] 이런 경우 topAnchor도 bottom을 기준으로 잡기보단, 높이가 80이란 것은 고정값인 것 같으니, 아래처럼 height로 주는 것이 가독성이 더 좋아보입니다.
```suggestion
            markerInfoView.heightAnchor.constraint(equalToConstant: 80),
```

2022-11-16 17:02 UTC, DevLuce reviewed
고생하셨습니다!! 많은 리뷰어들이 좋은 리뷰를 남겨주셨네용 💯

2022-11-16 17:02 UTC, DevLuce commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +class MapInfoView: UIView {
오 static dispatch, dynamic dispatch 배워갑니다!! 감사합니당 👍

2022-11-17 03:35 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +    var titleLabel: UILabel = {
수정했습니다.

2022-11-17 03:35 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        return title
수정했습니다.

2022-11-17 03:35 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        return imageView
수정했습니다.

2022-11-17 03:40 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        ])
이렇게 될 경우에 기기의 넓이가 0으로 변환됩니다.
차라리 trailingAnchor를 설정하지 않음으로 기기가 알아서 설정할 수 있도록 할까요?

2022-11-17 03:40 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +    }
확인하고 수정하겠습니다.

2022-11-17 03:40 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +class MapInfoView: UIView {
final 키워드로 빌드 속도 높이는쪽으로 하겠슴돠

2022-11-17 03:43 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +            markerImage.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 16)
오오 배워갑니다

2022-11-17 03:46 UTC, E-know commented on Workade/Views&ViewModels/Map/MapViewController.swift
> +            markerInfoView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -96),
수정했습니다!

2022-11-17 04:15 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        ])
맨 마지막 줄을
titleLabel.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -85)로 수정해보면 될 것 같습니당!

2022-11-17 04:22 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +class MapInfoView: UIView {
빌드 속도?는 잘 모르겠어용! 아마 컴파일 타임보단 런타임 성능 향상을 위한 방향일 겁니다~!

2022-11-17 04:24 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +class MapInfoView: UIView {
빌드 속도와도 관련이 있을지는 알아보고 다시 말씀드리겠습니당!

2022-11-17 04:30 UTC, BrightHyeon requested changes

2022-11-17 04:30 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
>              mapButton.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -16)
[P1] 새로 commit된 내용에서 mapButton의 레이아웃에 markerImage를 잡는 걸로 들어가있어서 수정해주시면 될것같아용!
mapButton.widthAnchor.constraint(equalTo: mapButton.heightAnchor) <- 👍

2022-11-17 04:32 UTC, BrightHyeon commented on Workade/Views&ViewModels/Map/MapInfoView.swift
> +        ])
엣지케이스일수도 있지만, trailingAnchor를 설정하지않을 경우 우측에 대한 제약조건이 없기 때문에 해당 장소(식당 등)의 이름이 굉장히 길 때, 레이블과 우측 맵 버튼이 겹치게 될 것입니다.

2022-11-17 05:20 UTC, jeohong approved these changes

2022-11-17 05:22 UTC, E-know commented on Workade/Views&ViewModels/Map/MapInfoView.swift
>              mapButton.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: -16)
앗 수정했습니다.

2022-11-17 06:02 UTC, BrightHyeon approved these changes
수고하셨습니당!

2022-11-17 06:09 UTC, merged