✨TipDetailView의 UI를 구현하였습니다.
IIION/Workade pull request #9
Opened 2022-10-21 12:52 UTC by jeohong

# 배경
- 팁 탭을 누를때 TipDetailView가 뜨도록 구현하였습니다.

# 작업 내용
- TipDetailView의 UI를 구성하였습니다.

# 테스트 방법
- 방법 1. SceneDelegate 파일에서 기존의 view?.rootViewController를 window?.rootViewController = MagazineViewController() 로 수정하여 실행합니다.
- 방법 2. 프리뷰 코드를 활용해 확인할수 있습니다.

# 리뷰 노트
- 현재 임시데이터를 넣어놓은 상태입니다. 추후 변경될 부분은 주석으로 달아 놓았습니다.
- 디자인 가이드상 Tip 만 있기에 팁 탭을 하셔서 보시면 됩니다.

# 스크린샷
- <img width="300" alt="image" src="https://user-images.githubusercontent.com/96639917/197200077-9c2921cb-5643-421b-a45e-887e0f11a97d.png">

2022-10-22 02:28 UTC, E-know commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        // todo: 추후 데이터 연결하여 동적으로 이미지 받아오도록 수정
[P3]todo는 눈에 띄도록 //TODO: 코멘트 형태 부탁드립니다!

2022-10-22 02:28 UTC, E-know commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +    // todo: 임시 데이터 -> 추후 요청으로 수정
[P3]이 역시 TODO로 수정이 어떨까요?

2022-10-22 02:42 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        // todo: 추후 데이터 연결하여 동적으로 이미지 받아오도록 수정
TODO로 작성하였으나 Lint 경고가 발생하여 소문자로 변경하였습니다. 일단은 워닝을 무시하고 대문자로 바꾸어 놓을까요?

2022-10-22 02:43 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +    // todo: 임시 데이터 -> 추후 요청으로 수정
위 내용과 동일합니다!

2022-10-22 06:21 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        // todo: 추후 데이터 연결하여 동적으로 이미지 받아오도록 수정
일단은 경고 무시하고 대문자 Mark 형식으로 수정해 놓았습니다!

2022-10-22 10:33 UTC, DevLuce reviewed
확인 완료했습니다!

2022-10-22 11:02 UTC, hs-ryu commented
확인 완료했습니다!

2022-10-22 11:32 UTC, E-know commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        // todo: 추후 데이터 연결하여 동적으로 이미지 받아오도록 수정
워닝이 디폴트 값이긴 한데 나중에 해야 할 일을 노티하는 기능으로도 충분하다고 생각됩니다!
개발하시면서 줄여갈 예정인 노티이기에 노티띄우는게 의미있지 않을까 생각합니다.

2022-10-22 11:38 UTC, E-know commented
<img src="https://user-images.githubusercontent.com/55151796/197336783-8fe5a40c-2787-45fe-ba11-7349c76e356c.png" height=300>
[P1]
- 높이가 고정으로 들어간 것 같습니다. 그로 인해서 사진 비율이 깨집니다. 조정 부탁드립니다. 
- 맥스버전에서는 위에 `NavigationBar` 부분이 크게 나오는데 임시로 넣은 네비게이션바에서 큰 것인지 아니면 `매거진`부분에서 큰 것인지 확인이 필요합니다.

2022-10-22 11:41 UTC, E-know requested changes
[P2] 생각하지 못했는데 개발과정에서도 저작권을 위해서 다른 사진을 이용하는게 좋을 것 같습니다!

2022-10-22 11:54 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        // todo: 추후 데이터 연결하여 동적으로 이미지 받아오도록 수정
확인했습니다!

2022-10-22 12:04 UTC, jeohong commented
> <img alt="" height="300" src="https://user-images.githubusercontent.com/55151796/197336783-8fe5a40c-2787-45fe-ba11-7349c76e356c.png">
> 
> [P1] - 높이가 고정으로 들어간 것 같습니다. 그로 인해서 사진 비율이 깨집니다. 조정 부탁드립니다. - 맥스버전에서는 위에 `NavigationBar` 부분이 크게 나오는데 임시로 넣은 네비게이션바에서 큰 것인지 아니면 `매거진`부분에서 큰 것인지 확인이 필요합니다.

해당 사항 확인결과 Max 버전에서 상단이 내려온 이유는 Bottom 값을 고정으로 줘서 그런거 같습니다 임시뷰긴 해도 일관성을 위해 높이값으로 수정 하였습니다.

Figma의 디자인 가이드상 이미지 셀의 높이값은 220 으로 고정되어 있기 때문에 해당 값으로 할당 하였습니다.
이부분은 에반과 상의해봐야 할것 같습니다. 220 고정값이기 때문에 상단 임시내비바와 상관없이 사진 비율은 Max에서 동일하게 깨지네요 :(

2022-10-22 12:06 UTC, jeohong commented
> [P2] 생각하지 못했는데 개발과정에서도 저작권을 위해서 다른 사진을 이용하는게 좋을 것 같습니다!

확인 했습니다 :) 임시 이미지를 수정하겠습니다

2022-10-22 17:41 UTC, eraser3031 requested changes
사소한 수정 사항만 반영해주시면 감사하겠습니다! 수고 많으셨습니다!!!

2022-10-22 17:41 UTC, eraser3031 commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +
```suggestion
        flowLayout.minimumLineSpacing = 20
```
[P1] 셀 간 여백 설정을 20으로 맞춰주시면 감사하겠습니다!!

2022-10-22 17:41 UTC, eraser3031 commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +    }
```suggestion
    @objc
    func clickedBookmarkButton(sender: UIButton) {
        var image: UIImage?
        let config = UIImage.SymbolConfiguration(pointSize: 17, weight: .semibold)
        if sender.currentImage == UIImage(systemName: "bookmark", withConfiguration: config) {
            image = UIImage(systemName: "bookmark.fill", withConfiguration: config)
            sender.setImage(image, for: .normal)
        } else {
            image = UIImage(systemName: "bookmark", withConfiguration: config)
            sender.setImage(image, for: .normal)
        }
    }
```

[P2] 북마크 버튼 굵기를 반영하는 코드를 추가했습니다!! 따로 SF 이미지에 대한 폰트 가이드라인이 없어서 설명이 부족했던 것 같아 죄송스럽습니다..

2022-10-22 17:41 UTC, eraser3031 commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +    }
[P5] 추가로 저는 @objc 또한 스유에서 @State, @Binding 등 @ 키워드를 이어서 쓰던 습관이 있어서 한줄로 붙여쓰곤 하는데 @objc을 따로 줄바꿈을 하신 이유가 있으신가요?? 이점이 있다면 알려주시면 감사하겠습니다!

2022-10-22 17:41 UTC, eraser3031 commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        button.setImage(UIImage(systemName: "bookmark"), for: .normal)
```suggestion
        let config = UIImage.SymbolConfiguration(pointSize: 17, weight: .semibold)
        button.setImage(UIImage(systemName: "bookmark", withConfiguration: config), for: .normal)
```

[P1] 북마크 버튼의 굵기를 반영시켰습니다!

2022-10-23 07:50 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +
반영 하였습니다 :)

2022-10-23 07:55 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
> +    }
[P2] 반영하였습니다.

[P5] 별 다른 이점없이 Lint 오류가 발생하여 개행을 넣었습니다. SwiftLint에서 잡더라구요 👍

2022-10-23 07:56 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
> +        button.setImage(UIImage(systemName: "bookmark"), for: .normal)
반영 하였습니다 :)

2022-10-24 10:37 UTC, DevLuce reviewed
확인했습니다!

2022-10-24 10:37 UTC, DevLuce commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +       let view = UIView()
[P1] 코드 indent가 맞지 않는것 같습니다. 수정 부탁드려요!

2022-10-24 10:37 UTC, DevLuce commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +       let button = UIButton()
[P1] 마찬가지로 코드 indent 확인 부탁드려요!

2022-10-24 10:47 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +       let view = UIView()
반영 했습니다 :)

2022-10-24 10:47 UTC, jeohong commented on Workade/Views&ViewModels/Magazine/MagazineViewController.swift
> +       let button = UIButton()
반영 했습니다 :)

2022-10-24 16:35 UTC, E-know approved these changes

2022-10-25 05:26 UTC, eraser3031 approved these changes

2022-10-25 06:02 UTC, merged