✨ 스티커를 획득하는 프로그레스뷰 UI를 추가하였습니다.
IIION/Workade pull request #93
Opened 2022-11-24 08:57 UTC by DevLuce

# 배경
- 워케이션뷰 하단 스티커 획득 프로그레스뷰 UI 구현

# 작업 내용
- 워케이션뷰 하단 스티커 획득 프로그레스뷰 UI 구현

# 테스트 방법
- SceneDelegate에서 window?.rootViewController = UINavigationController(rootViewController: WorkationViewController()) 로 변경하여 실행
- StickerProgressView 에서 Preview 가능하도록 일단 해놓았습니다. 최종 수정 이후에 삭제하겠습니다.

# 리뷰 노트
- 일단 초안 UI 입니다. 디테일하게 구현하기 위해서 지속적인 수정이 필요할 거 같습니다.
- 함께 UI 수정이 이뤄졌으면 해서 PR 올립니다. 

# 스크린샷
<img width="50%" alt="스크린샷 2022-11-24 오후 5 31 28" src="https://user-images.githubusercontent.com/56063805/203737157-f43cfcb9-9fb3-4619-941f-691d5149794c.png">
- progressStack 내에 빈뷰와 progressView 가 있습니다.
- lockStack 내에 여러개의 빈뷰와 weekStack 이 있습니다.
- 두 스택이 겹쳐져 있습니다.

2022-11-24 12:37 UTC, E-know requested changes
<img src="https://user-images.githubusercontent.com/55151796/203786013-1112c2c1-7860-4476-83b3-9ea3dea09c20.png" height=500>
@eraser3031 이건 에반의 의견이 필요합니다. 아이폰 SE3에서 이미지가 너무 작게 표시됩니다. 수정이 필요하다고 생각됩니다.

코드는 으역시 깔끔합니다.
[![LGTM](https://lgtm.lol/p/9)](https://lgtm.lol/i/9)

2022-11-24 12:37 UTC, E-know commented on Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
> +#endif
[P2] 미리보기는 삭제하는게 좋을 것 같습니다!

2022-11-24 12:37 UTC, E-know commented on Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressViewModel.swift
> +}
[P1] 사용하지 않는다면 삭제해주세요. 추후에 사용할 예정이라면 사용할 때에 PR올리는게 좋을 것 같습니다!

2022-11-25 05:38 UTC, hs-ryu approved these changes
확인했습니다!! 수고하셨습니다

2022-11-25 06:20 UTC, jeohong approved these changes
확인 했습니다 수고하셨습니다~!!

2022-11-25 06:22 UTC, DevLuce commented on Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
> +#endif
이 뷰가 추후에도 프리뷰로 보면서 작업할 부분이 많아서 일단 코드를 남겨둔채로 PR하였습니다! DEBUG 빌드시에만 빌드되도록 조건 처리하여서 RELEASE 에서는 빌드되지 않도록 하였는데 일단은 남겨두어도 괜찮을까요?

2022-11-25 06:23 UTC, DevLuce commented on Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressViewModel.swift
> +}
네 반영했습니다!

2022-11-25 06:24 UTC, DevLuce commented
> <img alt="" height="500" src="https://user-images.githubusercontent.com/55151796/203786013-1112c2c1-7860-4476-83b3-9ea3dea09c20.png">
> 
> @eraser3031 이건 에반의 의견이 필요합니다. 아이폰 SE3에서 이미지가 너무 작게 표시됩니다. 수정이 필요하다고 생각됩니다.
> 
> 코드는 으역시 깔끔합니다.
> 
> [![LGTM](https://camo.githubusercontent.com/9617e8402d3c798ba6775bab554b2f7dec304da693f365102924b5885c502258/68747470733a2f2f6c67746d2e6c6f6c2f702f39)](https://lgtm.lol/i/9)

에반과 함께 검토하였습니다!! 뷰에 큰 변화가 올것 같군요ㅎㅎ

2022-11-25 06:29 UTC, E-know commented on Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
> +#endif
issue로 올라간 다음에 realease 브랜치 때에는 삭제되어야 한다고 생각됩니다!

2022-11-28 06:10 UTC, E-know approved these changes

2022-11-28 06:10 UTC, merged