✨ ExploreViewController를 추가했습니다.
IIION/Workade pull request #94
Opened 2022-11-24 09:07 UTC by eraser3031

# 배경
- 2차 하이파이에 새로운 홈이 될 ExploreViewController를 작업이 요구되었습니다.
- 해당 파트 개발을 위해 지역을 대표할 배경, 여러 다양한 아이콘 이미지 에셋의 추가가  필요했습니다.

# 작업 내용
## ExploreViewController UI 구성 및 타 뷰컨트롤러 연결
- 지도를 보고 워케이션을 진행할 장소에 얼마나 많은 인원이 있는 지 확인하고 내 정보, 오픈 채팅, 가이드 등 다른 뷰로 이동할 줄기가 되어줄 ExploreViewController의 UI를 구성 및 타 뷰 컨트롤러와 연결 작업을 진행했습니다.
- 전국 8도 및 제주도를 대표할 배경 이미지 에셋 및 워케이션 버튼에 있는 별 이미지 에셋을 추가했습니다.
- 지역 선택 시 밑에 인원수 및 워케이션 뷰로 이동할 버튼을 표시해줄 커스텀 UIView인 RegionInfoView를 추가했습니다.
## 뷰 구성
<img width="600" alt="스크린샷 2022-10-19 오후 5 50 31" src="https://user-images.githubusercontent.com/63719961/203733669-134a2463-9c78-48df-98d3-c4e1c364cf79.png">
<img width="600" alt="스크린샷 2022-10-19 오후 5 50 31" src="https://user-images.githubusercontent.com/63719961/203732975-a36717ad-c2f1-4607-bd29-ab9d5ccda8ef.png">

# 테스트 방법
- 해당 브랜치에서 작업물을 실행해주세요.
- 시뮬레이터 및 실기기를 통해 다양한 레이아웃에서도 UI가 정상적으로 보여지는 지 확인해주세요.
- 가이드 / 오픈채팅 / 내 정보 버튼 터치 시 정상적으로 해당 뷰컨트롤러로 Navigate 되는 지 확인해주세요.
- 각 지역 버튼 터치 시 애니메이션이 제대로 보여지는 지 확인해주세요.

# 리뷰 노트
- **애니메이션에 대해**
지역 버튼 선택 유무에 따라 전환되는 UI 애니메이션의 경우 iOS 10에 도입된 UIViewPropertyAnimator를 활용하여 개발했습니다. 현재 해당 클래스에 대해 더 공부해볼 파트가 많고 현재 A상태 -> B상태 애니메이션이 진행되고 있는 도중 액션을 취해 다시 B상태 -> A상태의 애니메이션으로 돌아가는 경우 애니메이션이 제대로 작동하지 않는 이슈가 존재합니다. 제 추정으로는 지금의 코드가 Interruptible한 애니메이션에 대해 제대로 대응하지 못하고 있다고 생각해서 WWDC "Advanced Animations with UIKit" 세션을 학습하고 다시 한 번 리펙토링을 진행해볼 계획이니 해당 부분에 대해서 알고 계시거나 도움을 주실 수 있는 부분이 있다면 해당 파트를 중점으로 리뷰 남겨주시면 감사하겠습니다.

- **mapImageView 및 RegionButton 위치 지정 방식에 대해**
mapImageView와 RegionButton의 위치를 다양한 크기의 디바이스에서 깨지지 않도록 유지하기 위해 많은 시간이 들였습니다. mapImageView의 경우 top, bottom 앵커만 잡아주고 크기 자체는 imageView의 contentMode를 .scaleAspectFill로 두어 이미지 자체의 Intrinsic Size에 의존하고 있습니다. 대한민국 지도 너비/높이 비율이 어떠한 아이폰의 세로모드 사이즈의 너비/높이 비율보다 높지 않아 이미지가 화면 좌우로 넘어가는 일이 없습니다. 
RegionButton의 경우 Figma에서 지도 이미지를 좌표평면 삼아 중심에서 몇 퍼센트 벗어났는 지를 RegionModel의 계산 프로퍼티로 CGPoint 값을 얻을 수 있도록 했고 해당 값을 실제 이미지의 높이, 너비값과 곱해줘서 기기에 따라 지도 이미지 크기가 달라지더라도 동일한 버튼 위치로 이동할 수 있도록 했습니다.

- **디자인 패턴에 대해**
현재 ExploreViewController의 뷰모델에 있는 selectedRegion Binder의 상태에 따라 뷰가 업데이트되고 있습니다.  ExploreViewController가 가지고 있는 전국 8도에 해당하는 각각의 RegionButton를 터치 할 시 해당 상태가 변경되는 로직을 취하고 있는 데 이를 위해서 각각의 RegionButton은 마치 SwiftUI의 @Binding과 같은 패턴처럼 binder를 프로퍼티로 받아서 해당 binder를 변경하는 로직을 해당 뷰의 UIAction 클로저에 넣어주고 있습니다. 해당 로직이 UIKit에서 MVVM 패턴을 사용하는 데 적합한 구성인지 모호하다고 느껴서 많은 피드백 부탁드립니다.(Combine 경험이 있으시다면 더더욱 부탁드려용ㅎㅎ..)

2022-11-24 12:39 UTC, E-know commented
리뷰하기 전 부터 이미지로 요약이 너무 좋아서 LGTM 달고 리뷰 합니다.
[![LGTM](https://lgtm.lol/p/9)](https://lgtm.lol/i/9)

2022-11-24 13:31 UTC, E-know requested changes
<p>
<img src="https://user-images.githubusercontent.com/55151796/203794884-8b7d359d-cfdc-491d-98c6-d26c0ca130c5.png" height=350>
<img src="https://user-images.githubusercontent.com/55151796/203794903-6490ecc1-98e3-4349-aa14-7bd520572f88.png" height=350>
<img src="https://user-images.githubusercontent.com/55151796/203794952-3ddf86a3-47b0-4749-b6d3-5645ffa9eeb9.png" height=350>
</p>
(왼쪽 부터 1번 2번 3번 사진)

기종 : iPhoneSE 3rd Generation

시뮬 : 제주도 클릭 후에 하단 모달 X 버튼으로 다시 빠져 나왔음. 

문제점

1. (1번 사진)에서 제주도 버튼이 하단 모달을 침범함.
2. 클릭 후에 제주도 위치를 다시 못잡고 하단 모달을 심하게 침범함
- - -
코드 전체 캡슐화가 안되어 있는 것 같습니다. 외부에서 사용하지 않는다면 private를 걸어주세요.

2022-11-24 13:31 UTC, E-know commented on Workade/Models/RegionModel.swift
> +    }
```suggestion
    var imageName: String {
        return self.rawValue + "Background"
    }
```
[P3] 추가적인 변수명을 둔 이유가 궁금합니다.

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +
[P4] 필요없는 공백은 삭제해주세요.

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +    var regionInfoViewBottomConstraint: NSLayoutConstraint?
[P2] 외부에서 접근을 `private`로 막아주세요!

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +    }
[P1] forEach 및 addAnimations도 Closure 형태라서 강한 참조가 발생합니다!
둘다 [weak self]로 바꿔주세요.

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }, completion: nil)
[P1] 강한 참조 유의해주세요!

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/RegionInfoView.swift
> +    let selectedRegion: Binder<RegionModel?>
[P3] 필요 없는 공백은 삭제 부택드려요!

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +class ExploreViewController: UIViewController {
[P1] 더 이상 상속을 하지 않는다면 final로 선언 해주세요.
```suggestion
final class ExploreViewController: UIViewController {
```

2022-11-24 13:31 UTC, E-know commented on Workade/Views&ViewModels/Explore/RegionInfoView.swift
> +class RegionInfoView: UIView {
[P1] 더 이상 상속하지 않는다면 final 선언 부탁드립니다.
```suggestion
final class RegionInfoView: UIView {
```

2022-11-24 13:31 UTC, E-know commented on Workade/Share/RegionButton.swift
> +class RegionButton: UIButton {
[P1] 더 이상 상속하지 않는다면 final 선언 부탁드립니다.
```suggestion
final class RegionButton: UIButton {
```

2022-11-25 06:06 UTC, hs-ryu approved these changes
확인했습니다! 수고하셨습니다.

2022-11-25 06:21 UTC, eraser3031 commented on Workade/Models/RegionModel.swift
> +    }
처음 구현할 당시 해당 모델의 다른 계산 프로퍼티 처럼 switch self { ...} 으로 케이스별로 리턴해주는 방식이어서 여러군데에서 같은 String값을 써 하나의 변수로 빼줬는데 self.rawValue로 한 문장으로 선언가능해져서 따로 빼둘 필요가 없어졌네요. 좋은 지적 감사합니다!

2022-11-25 06:25 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +
수정했습니다!!

2022-11-25 06:25 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +    var regionInfoViewBottomConstraint: NSLayoutConstraint?
수정했습니다!!

2022-11-25 06:25 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/RegionInfoView.swift
> +    let selectedRegion: Binder<RegionModel?>
수정했습니다!!

2022-11-25 06:25 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +class ExploreViewController: UIViewController {
수정했습니다!!

2022-11-25 06:28 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/RegionInfoView.swift
> +class RegionInfoView: UIView {
final을 자주 깜빡깜빡하네용..ㅠ 수정했습니다!!

2022-11-25 06:28 UTC, eraser3031 commented on Workade/Share/RegionButton.swift
> +class RegionButton: UIButton {
수정했습니다!!

2022-11-25 06:36 UTC, jeohong requested changes
토비의 코드리뷰가 깔끔해서 제가 더이상 리뷰할 내용은 없을것 같습니다 
수고 하셨서요 에반~!

iPhone SE 에서 깨지는 현상과, 약한참조만 수정하면 될것같습니다~

2022-11-25 06:43 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }, completion: nil)
UIView.transition, UIView.animate는 타입 메소드라 인스턴스를 만들 지 않고 바로 생성해서 참조 카운트가 증가하지 않는다~ 같은 이야기를 들은 적이 있어서 배제하고 코드를 작성했는데 검색해보니 제 생각보다 더 깊이가 있고 공부가 필요한 내용인 것 같네요. 리뷰해주신대로 반영하고 좀 더 해당 파트에 대해 공부해보겠습니다!

2022-11-25 06:48 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +    }
forEach는 예상못했네요 감사합니다. 수정했습니다!

2022-11-25 07:06 UTC, DevLuce reviewed
굳굳 고생하셨습니다!! 뷰 표시 짱이군요ㅠㅠ 역시 갓반..

2022-11-25 07:06 UTC, DevLuce commented on Workade/Share/RegionButton.swift
> +    }
[P3] changeLayout 함수를 setupLayout 함수 안에서 호출하는 이유가 있을까요?? init 안에서 setupLayout 다음에 호출하는 건 어떨까요??

2022-11-25 07:06 UTC, DevLuce commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }
[P3] 클로저라고 항상 [weak self]를 달아야할까요?? non-escaping 클로저의 경우에는 순환 참조가 일어나지 않는다고 하는데 forEach는 non-escaping인 것 같습니다! 제가 아직 부족해서 잘 모르지만 이런식으로 모든 클로저에 항상 [weak self]를 달아야하는지에 대한 여부는 같이 인사이트를 나누면 좋을 거 같습니다!

2022-11-25 07:09 UTC, DevLuce commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }
forEach 와 같은 고차함수이 filter에 weak self 를 써야하는 지에 대한 질문이 애플 포럼에 올라와서 링크 첨부합니다!
https://developer.apple.com/forums/thread/118546

2022-11-28 06:11 UTC, jeohong approved these changes

2022-11-28 06:11 UTC, E-know approved these changes

2022-11-28 07:44 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }
생각해보니 non-escaping 클로저는 생성된 함수 컨텍스트 내부에서만 존재하니 일반적으로는 weak self를 쓸 필요가 없겠네요. 좋은 지적과 링크 첨부 감사합니다!!

2022-11-28 07:46 UTC, eraser3031 commented on Workade/Views&ViewModels/Explore/ExploreViewController.swift
> +            }
이외에도 weak self를 쓸 때마다 아직 스스로 확신이 없어서 다음 TOD 기회가 있다면 캡쳐 리스트 관련해서 공부해와보겠습니다!

2022-11-28 10:58 UTC, merged