✨ 로그인 회원가입 View를 구현하였습니다.
IIION/Workade pull request #95
Opened 2022-11-24 12:25 UTC by E-know

# 배경
- 회원가입시 연결해야 하는 View 구현

# 작업 내용
- 이름을 입력 받을 수 있는 View 구현
- 직업을 선택할 수 있는 직업 View 구현

# 테스트 방법
- `SceneDelegate`에서 22번째 줄을 
`window?.rootViewController = UINavigationController(rootViewController: LoginNameViewController())`
으로 변경

# 리뷰 노트
- MVVM 분리가 적절한지 봐주시면 감사하겠습니다.
- 화면 전환 및 NextButton이 정상적으로 애니메이션 및 작동하는지 봐주셨으면 좋겠습니다.

# 스크린샷
![Frame 1](https://user-images.githubusercontent.com/55151796/203783885-1e1f9761-987d-4079-8ffd-579d8bdf18c9.png)

2022-11-25 06:18 UTC, hs-ryu approved these changes
확인했습니다. Dropdown 메뉴 디자인 관련하여 머지 이후에 치콩이 작성한 쪽과 맞춰야할 것 같습니다.

2022-11-25 06:43 UTC, jeohong requested changes
[P1] UX관점에서 3가지의 수정사항을 반영하였으면 합니다!
1. 텍스트 필드 입력시 키보드 올라왔을때 return 버튼 터치할때 처리
2. 텍스트필드 이외의 곳을 터치할때 키보드 내리기
3. 피커가 내려간 상태에서 피커 이외의 영역을 터치할때 피커 닫히도록 처리

+) 프로필 수정에 있는 피커와 통일된 디자인이 필요할것 같으나 해당 부분은 머지이후 새로이 작업하면 될것 같습니다! @eraser3031  어떤 디자인으로 들고갈지 나중에 고민해봐요!

2022-11-25 07:33 UTC, DevLuce reviewed
고생하셨습니다!!

2022-11-25 07:33 UTC, DevLuce commented on Workade/Extentions/UIVIew+.swift
> +//        gradient.locations = [0.0, 1.0]
[P2] 주석처리된 코드는 지워주시면 좋을것 같아용!

2022-11-25 07:33 UTC, DevLuce commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +    lazy private var defaultPickerImage: UIImageView = {
[P5] private lazy var 로 통일하는건 어떨까요??

2022-11-25 07:33 UTC, DevLuce commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +        }, for: .touchUpInside)
[P3] setupLayout 함수 내에 이 로직이 위치할 필요가 있을까요?

2022-11-28 12:04 UTC, E-know commented
> [P1] UX관점에서 3가지의 수정사항을 반영하였으면 합니다!
> 
> 1. 텍스트 필드 입력시 키보드 올라왔을때 return 버튼 터치할때 처리
> 2. 텍스트필드 이외의 곳을 터치할때 키보드 내리기
> 3. 피커가 내려간 상태에서 피커 이외의 영역을 터치할때 피커 닫히도록 처리
> 
> +) 프로필 수정에 있는 피커와 통일된 디자인이 필요할것 같으나 해당 부분은 머지이후 새로이 작업하면 될것 같습니다! @eraser3031 어떤 디자인으로 들고갈지 나중에 고민해봐요!

오 UX관점에서 아주 좋은 피드백 같습니다 수정했습니다!

2022-11-28 12:07 UTC, E-know commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +    lazy private var defaultPickerImage: UIImageView = {
모두 다 수정했습니다!

2022-11-28 12:09 UTC, E-know commented on Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
> +        }, for: .touchUpInside)
의미가 안 맞다는 생각이 듭니다 함수 분리했습니다!

2022-11-28 12:39 UTC, DevLuce approved these changes
고생했어요!!

2022-11-28 12:58 UTC, jeohong commented
> > [P1] UX관점에서 3가지의 수정사항을 반영하였으면 합니다!
> > 
> > 1. 텍스트 필드 입력시 키보드 올라왔을때 return 버튼 터치할때 처리
> > 2. 텍스트필드 이외의 곳을 터치할때 키보드 내리기
> > 3. 피커가 내려간 상태에서 피커 이외의 영역을 터치할때 피커 닫히도록 처리
> > 
> > +) 프로필 수정에 있는 피커와 통일된 디자인이 필요할것 같으나 해당 부분은 머지이후 새로이 작업하면 될것 같습니다! @eraser3031 어떤 디자인으로 들고갈지 나중에 고민해봐요!
> 
> 오 UX관점에서 아주 좋은 피드백 같습니다 수정했습니다!

브랜치의 최신 상태에서 
![image](https://user-images.githubusercontent.com/96639917/204283451-86fb6353-bf72-4e68-a5d2-e86a94d130e0.png)

StickerProgressViewModel 관련하여 실행되지 않습니다 확인 부탁드려요!

2022-11-28 13:39 UTC, E-know commented
> > > [P1] UX관점에서 3가지의 수정사항을 반영하였으면 합니다!
> > > 
> > > 1. 텍스트 필드 입력시 키보드 올라왔을때 return 버튼 터치할때 처리
> > > 2. 텍스트필드 이외의 곳을 터치할때 키보드 내리기
> > > 3. 피커가 내려간 상태에서 피커 이외의 영역을 터치할때 피커 닫히도록 처리
> > > 
> > > +) 프로필 수정에 있는 피커와 통일된 디자인이 필요할것 같으나 해당 부분은 머지이후 새로이 작업하면 될것 같습니다! @eraser3031 어떤 디자인으로 들고갈지 나중에 고민해봐요!
> > 
> > 
> > 오 UX관점에서 아주 좋은 피드백 같습니다 수정했습니다!
> 
> 브랜치의 최신 상태에서 ![image](https://user-images.githubusercontent.com/96639917/204283451-86fb6353-bf72-4e68-a5d2-e86a94d130e0.png)
> 
> StickerProgressViewModel 관련하여 실행되지 않습니다 확인 부탁드려요!

수정했습니다.

2022-11-28 13:52 UTC, jeohong commented
[P3]
1. 키보드 상에서 return 키를 눌러도 전달이 되지 않는것 같습니다..!
2. 피커 뜨는 뷰에서 버튼 외의 영역을 터치해도 피커가 뜨는것 같아요!

https://user-images.githubusercontent.com/96639917/204294317-c6deed66-47e5-418c-86e2-1a71ef847cdd.mov


https://user-images.githubusercontent.com/96639917/204294339-3a592cda-d69b-401c-847e-1c48ea3d93fa.mov

2022-11-28 15:28 UTC, E-know commented
> [P3]
> 
> 1. 키보드 상에서 return 키를 눌러도 전달이 되지 않는것 같습니다..!
> 2. 피커 뜨는 뷰에서 버튼 외의 영역을 터치해도 피커가 뜨는것 같아요!
> 
>  2022-11-28.10.50.25.mov 
> 
>  2022-11-28.10.50.41.mov

수정했습니다!

2022-11-29 01:57 UTC, jeohong approved these changes
깔끔하게 동작하네요 수고하셨습니다 토비!!

2022-11-29 01:58 UTC, merged