✨ OfficeCell과 MagazineCell을 눌러 present할 때 Transition 애니메이션을 적용했습니다.
IIION/Workade pull request #99
Opened 2022-11-26 08:31 UTC by BrightHyeon

# 배경
- 홈 디자인이 인터렉티브하기에 마찬가지로 좀 더 인터렉티브한 트랜지션이 있으면 더 일관된 UX를 제공할 수 있을 듯 했다.

# 작업 내용
- 홈, 오피스뷰컨, 매거진뷰컨 등에서 셀을 클릭하면, 해당하는 Sheet를 기존 fullScreen 모달 형태가 아닌 custom 형태가 되도록 구현했습니다.

# 테스트 방법
- 시뮬레이터 켜서 가이드홈, 지역별 오피스 페이지, 전체 매거진 페이지 등에서 present, dismiss 등을 해보시면 됩니다.

# 리뷰 노트
- 이번 PR 변경점이 많습니다. 유의해주세요. (이렇게 길어질지 몰랐습니다...)
- 스스로 리팩토링의 여지가 많은 코드라 생각하여 반영할지 말지 고민을 많이 했었습니다. 개선의 여지가 보인다면 많은 suggestion 부탁드립니다.
- 여러 곳, 여러 셀에서 마구마구 눌러보시면 됩니다. 혹시 모를 버그가 있는지 체크해주세요.
- 북마크 버튼도 함께 많이 눌러보며, 잘 반영되는지 버그는 없는지 체크해주세요.
- 뒤늦게 snapshotView 기능을 알아서, 인스타그램 스타일 버전을 만들어봤으나 기존 앱스토어 스타일이 이쁜 듯하여 앱스토어 버전으로 PR올렸습니다.
- 앱스토어 스타일도 snapshotView 이용하여 코드를 간소화하려했으나, 기존 구현이 코드는 길지만 더 통통 튀는 느낌이 잘 살아서 기존 PR로 올렸습니다.

# 스크린샷
<div>
<img src = "https://user-images.githubusercontent.com/95853235/204079750-6974d926-93f7-4f53-9c05-76dff87a054b.gif" width = "300">
<img src = "https://user-images.githubusercontent.com/95853235/204079765-44a5f289-5780-4fc6-8df3-a060ac785f99.gif" width = "300">
</div>

2022-11-26 12:33 UTC, DevLuce approved these changes
와우 역시 애니메이션의 장인 탐나! 깔끔합니다!! 고생 많으셨어용 :) 버그도 제가 확인한바로는 없었습니다!

2022-11-26 12:33 UTC, DevLuce commented on Workade/Managers/MagazineTransitionManager.swift
> +        }
[P3] 우리팀 코드 컨벤션에 따라 VC와 같은 축약형은 지양하는게 좋을거 같습니다!

2022-11-28 03:51 UTC, jeohong requested changes
실행 시 버그는 없었습니다 역시 깔끔하네요.. 탐나 수고하셨어요!! 

컨벤션에 맞게 일부 코드만 수정 부탁드려요!

2022-11-28 03:51 UTC, jeohong commented on Workade.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = B2RV52W8G3;
[P1] Team 사이닝 비워주세요!

2022-11-28 03:51 UTC, jeohong commented on Workade/Managers/MagazineTransitionManager.swift
> +        let toVC = transitionContext.viewController(forKey: .to)
[P3]
```suggestion
        let fromViewController = transitionContext.viewController(forKey: .from)
        let toViewController = transitionContext.viewController(forKey: .to)
```

수정 부탁드립니다!

2022-11-28 03:51 UTC, jeohong commented on Workade/Managers/MagazineTransitionManager.swift
> +        return downstairsConstraints
[P3] return 전에 공백 추가 부탁드려요!

2022-11-28 03:51 UTC, jeohong commented on Workade/Managers/MagazineTransitionManager.swift
> +        return upstairsConstraints
[P3] return 전에 공백 추가 부탁드려요!

2022-11-28 03:51 UTC, jeohong commented on Workade/Managers/OfficeTransitionManager.swift
> +        return downstairsConstraints
[P3] return 전에 공백추가 부탁드려요!

2022-11-28 03:51 UTC, jeohong commented on Workade/Managers/OfficeTransitionManager.swift
> +        return upstairsConstraints
[P3] return 전에 공백추가 부탁드려요!

2022-11-28 07:56 UTC, eraser3031 reviewed
탐나 PR을 코드리뷰 할 때마다 잘 정리된 주석과 읽기 쉬운 코드 정리 덕분에 너무 보기 편한 것 같습니다!!

저도 치콩이 말씀하신 수정사항만 반영해주시면 될 것 같습니다!!

2022-11-28 08:27 UTC, BrightHyeon commented on Workade/Managers/MagazineTransitionManager.swift
> +        }
수정했습니당~!

2022-11-28 08:28 UTC, BrightHyeon commented on Workade.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = B2RV52W8G3;
수정했습니당~!

2022-11-28 08:30 UTC, BrightHyeon commented on Workade/Managers/OfficeTransitionManager.swift
> +        return upstairsConstraints
공백 및 사이닝 수정했습니당~!

2022-11-28 09:23 UTC, jeohong approved these changes

2022-11-28 09:23 UTC, merged